// ================================================
// WARNING: This file is automatically generated.
// Do not modify it by hand. Your changes will be
// overwritten the next time the generator runs.
// ================================================

import { rpcCall } from '../../../shared/RpcModels';

export const fetchMembers = (payload: any = null): Promise<any> => rpcCall('urn:support:roles:get_members:1', payload);
export const fetchAddMember = (payload: any = null): Promise<any> => rpcCall('urn:support:roles:add_member:1', payload);
export const fetchRemoveMember = (payload: any = null): Promise<any> => rpcCall('urn:support:roles:remove_member:1', payload);
