// ================================================
// WARNING: This file is automatically generated.
// Do not modify it by hand. Your changes will be
// overwritten the next time the generator runs.
// ================================================

import { rpcCall } from '../../../shared/RpcModels';

export const fetchList = (payload: any = null): Promise<any> => rpcCall('urn:users:products:list:1', payload);
export const fetchPurchase = (payload: any = null): Promise<any> => rpcCall('urn:users:products:purchase:1', payload);
