// ================================================
// WARNING: This file is automatically generated.
// Do not modify it by hand. Your changes will be
// overwritten the next time the generator runs.
// ================================================

import { rpcCall } from '../../../shared/RpcModels';

export const fetchCreate = (payload: any = null): Promise<any> => rpcCall('urn:finance:ledgers:create:1', payload);
export const fetchDelete = (payload: any = null): Promise<any> => rpcCall('urn:finance:ledgers:delete:1', payload);
export const fetchGet = (payload: any = null): Promise<any> => rpcCall('urn:finance:ledgers:get:1', payload);
export const fetchList = (payload: any = null): Promise<any> => rpcCall('urn:finance:ledgers:list:1', payload);
export const fetchUpdate = (payload: any = null): Promise<any> => rpcCall('urn:finance:ledgers:update:1', payload);
