// ================================================
// WARNING: This file is automatically generated.
// Do not modify it by hand. Your changes will be
// overwritten the next time the generator runs.
// ================================================

import { rpcCall } from '../../../shared/RpcModels';

export const fetchFiles = (payload: any = null): Promise<any> => rpcCall('urn:storage:files:get_files:1', payload);
export const fetchUploadFiles = (payload: any = null): Promise<any> => rpcCall('urn:storage:files:upload_files:1', payload);
export const fetchDeleteFiles = (payload: any = null): Promise<any> => rpcCall('urn:storage:files:delete_files:1', payload);
export const fetchSetGallery = (payload: any = null): Promise<any> => rpcCall('urn:storage:files:set_gallery:1', payload);
export const fetchCreateFolder = (payload: any = null): Promise<any> => rpcCall('urn:storage:files:create_folder:1', payload);
export const fetchMoveFile = (payload: any = null): Promise<any> => rpcCall('urn:storage:files:move_file:1', payload);
export const fetchRenameFile = (payload: any = null): Promise<any> => rpcCall('urn:storage:files:rename_file:1', payload);
export const fetchLink = (payload: any = null): Promise<any> => rpcCall('urn:storage:files:get_link:1', payload);
export const fetchMetadata = (payload: any = null): Promise<any> => rpcCall('urn:storage:files:get_metadata:1', payload);
export const fetchFolderFiles = (payload: any = null): Promise<any> => rpcCall('urn:storage:files:get_folder_files:1', payload);
export const fetchDeleteFolder = (payload: any = null): Promise<any> => rpcCall('urn:storage:files:delete_folder:1', payload);
export const fetchCreateUserFolder = (payload: any = null): Promise<any> => rpcCall('urn:storage:files:create_user_folder:1', payload);
export const fetchUsage = (payload: any = null): Promise<any> => rpcCall('urn:storage:files:get_usage:1', payload);
export const fetchPublicFiles = (payload: any = null): Promise<any> => rpcCall('urn:storage:files:get_public_files:1', payload);
export const fetchModerationFiles = (payload: any = null): Promise<any> => rpcCall('urn:storage:files:get_moderation_files:1', payload);
export const fetchReportFile = (payload: any = null): Promise<any> => rpcCall('urn:storage:files:report_file:1', payload);
