// ================================================
// WARNING: This file is automatically generated.
// Do not modify it by hand. Your changes will be
// overwritten the next time the generator runs.
// ================================================

import { rpcCall } from '../../../shared/RpcModels';

export const fetchFiles = (payload: any = null): Promise<any> => rpcCall('urn:storage:files:get_files:1', payload);
export const fetchUploadFiles = (payload: any = null): Promise<any> => rpcCall('urn:storage:files:upload_files:1', payload);
export const fetchDeleteFiles = (payload: any = null): Promise<any> => rpcCall('urn:storage:files:delete_files:1', payload);
export const fetchSetGallery = (payload: any = null): Promise<any> => rpcCall('urn:storage:files:set_gallery:1', payload);
