// ================================================
// WARNING: This file is automatically generated.
// Do not modify it by hand. Your changes will be
// overwritten the next time the generator runs.
// ================================================

import { rpcCall } from '../../../shared/RpcModels';

export const fetchTrialBalance = (payload: any = null): Promise<any> => rpcCall('urn:finance:reporting:trial_balance:1', payload);
export const fetchJournalSummary = (payload: any = null): Promise<any> => rpcCall('urn:finance:reporting:journal_summary:1', payload);
export const fetchPeriodStatus = (payload: any = null): Promise<any> => rpcCall('urn:finance:reporting:period_status:1', payload);
export const fetchCreditLotSummary = (payload: any = null): Promise<any> => rpcCall('urn:finance:reporting:credit_lot_summary:1', payload);
