// ================================================
// WARNING: This file is automatically generated.
// Do not modify it by hand. Your changes will be
// overwritten the next time the generator runs.
// ================================================

import { rpcCall } from '../../../shared/RpcModels';

export const fetchRoles = (payload: any = null): Promise<any> => rpcCall('urn:service:roles:get_roles:1', payload);
export const fetchUpsertRole = (payload: any = null): Promise<any> => rpcCall('urn:service:roles:upsert_role:1', payload);
export const fetchDeleteRole = (payload: any = null): Promise<any> => rpcCall('urn:service:roles:delete_role:1', payload);
export const fetchRoleMembers = (payload: any = null): Promise<any> => rpcCall('urn:service:roles:get_role_members:1', payload);
export const fetchAddRoleMember = (payload: any = null): Promise<any> => rpcCall('urn:service:roles:add_role_member:1', payload);
export const fetchRemoveRoleMember = (payload: any = null): Promise<any> => rpcCall('urn:service:roles:remove_role_member:1', payload);
