// ================================================
// WARNING: This file is automatically generated.
// Do not modify it by hand. Your changes will be
// overwritten the next time the generator runs.
// ================================================

import { type ComponentType, type LazyExoticComponent } from 'react';

type PageRoute = {
	path: string;
	component: LazyExoticComponent<ComponentType<any>>;
};

const PAGE_ROUTES: PageRoute[] = [
];

export default PAGE_ROUTES;
