// ================================================
// WARNING: This file is automatically generated.
// Do not modify it by hand. Your changes will be
// overwritten the next time the generator runs.
// ================================================

import { rpcCall, SystemConfigList1 } from '../../../shared/RpcModels';

export const fetchList = (payload: any = null): Promise<SystemConfigList1> => rpcCall('urn:system:config:list:1', payload);
export const fetchSet = (payload: any = null): Promise<any> => rpcCall('urn:system:config:set:1', payload);
export const fetchDelete = (payload: any = null): Promise<any> => rpcCall('urn:system:config:delete:1', payload);
