// ================================================
// WARNING: This file is automatically generated.
// Do not modify it by hand. Your changes will be
// overwritten the next time the generator runs.
// ================================================

import { rpcCall } from '../../../shared/RpcModels';

export const fetchConfigs = (payload: any = null): Promise<any> => rpcCall('urn:system:config:get_configs:1', payload);
export const fetchUpsertConfig = (payload: any = null): Promise<any> => rpcCall('urn:system:config:upsert_config:1', payload);
export const fetchDeleteConfig = (payload: any = null): Promise<any> => rpcCall('urn:system:config:delete_config:1', payload);
