// ================================================
// WARNING: This file is automatically generated.
// Do not modify it by hand. Your changes will be
// overwritten the next time the generator runs.
// ================================================

import { rpcCall } from '../../../shared/RpcModels';

export const fetchApprove = (payload: any = null): Promise<any> => rpcCall('urn:finance:staging:approve:1', payload);
export const fetchDeleteImport = (payload: any = null): Promise<any> => rpcCall('urn:finance:staging:delete_import:1', payload);
export const fetchImport = (payload: any = null): Promise<any> => rpcCall('urn:finance:staging:import:1', payload);
export const fetchImportInvoices = (payload: any = null): Promise<any> => rpcCall('urn:finance:staging:import_invoices:1', payload);
export const fetchListImports = (payload: any = null): Promise<any> => rpcCall('urn:finance:staging:list_imports:1', payload);
export const fetchListDetails = (payload: any = null): Promise<any> => rpcCall('urn:finance:staging:list_details:1', payload);
export const fetchListLineItems = (payload: any = null): Promise<any> => rpcCall('urn:finance:staging:list_line_items:1', payload);
export const fetchPromote = (payload: any = null): Promise<any> => rpcCall('urn:finance:staging:promote:1', payload);
export const fetchReject = (payload: any = null): Promise<any> => rpcCall('urn:finance:staging:reject:1', payload);
