// ================================================
// WARNING: This file is automatically generated.
// Do not modify it by hand. Your changes will be
// overwritten the next time the generator runs.
// ================================================

import { rpcCall } from '../../../shared/RpcModels';

export const fetchPersonaCommand = (payload: any = null): Promise<any> => rpcCall('urn:discord:chat:persona_command:1', payload);
export const fetchPersonaResponse = (payload: any = null): Promise<any> => rpcCall('urn:discord:chat:persona_response:1', payload);
export const fetchPersona = (payload: any = null): Promise<any> => rpcCall('urn:discord:chat:get_persona:1', payload);
export const fetchConversationHistory = (payload: any = null): Promise<any> => rpcCall('urn:discord:chat:get_conversation_history:1', payload);
export const fetchChannelHistory = (payload: any = null): Promise<any> => rpcCall('urn:discord:chat:get_channel_history:1', payload);
export const fetchInsertConversationInput = (payload: any = null): Promise<any> => rpcCall('urn:discord:chat:insert_conversation_input:1', payload);
export const fetchGeneratePersonaResponse = (payload: any = null): Promise<any> => rpcCall('urn:discord:chat:generate_persona_response:1', payload);
export const fetchDeliverPersonaResponse = (payload: any = null): Promise<any> => rpcCall('urn:discord:chat:deliver_persona_response:1', payload);
export const fetchSummarizeChannel = (payload: any = null): Promise<any> => rpcCall('urn:discord:chat:summarize_channel:1', payload);
