version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mssql
    ports:
      - "8000:8000"
    environment:
      DATABASE_HOST: mssql
      DATABASE_USER: sa
      DATABASE_PASSWORD: ${MSSQL_ADMIN_PASSWORD}
      DATABASE_PORT: 1433

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      SA_PASSWORD: ${MSSQL_ADMIN_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
