// ================================================
// WARNING: This file is automatically generated.
// Do not modify it by hand. Your changes will be
// overwritten the next time the generator runs.
// ================================================

import { rpcCall, AdminLinksHome1, AdminLinksRoutes1 } from '../../../shared/RpcModels';

export const fetchHome = (payload: any = null): Promise<AdminLinksHome1> => rpcCall('urn:admin:links:get_home:1', payload);
export const fetchRoutes = (payload: any = null): Promise<AdminLinksRoutes1> => rpcCall('urn:admin:links:get_routes:1', payload);
