// ================================================
// WARNING: This file is automatically generated.
// Do not modify it by hand. Your changes will be
// overwritten the next time the generator runs.
// ================================================

import { rpcCall } from '../../../shared/RpcModels';

export const fetchList = (payload: any = null): Promise<any> => rpcCall('urn:finance:product_journal_config:list:1', payload);
export const fetchGet = (payload: any = null): Promise<any> => rpcCall('urn:finance:product_journal_config:get:1', payload);
export const fetchUpsert = (payload: any = null): Promise<any> => rpcCall('urn:finance:product_journal_config:upsert:1', payload);
export const fetchApprove = (payload: any = null): Promise<any> => rpcCall('urn:finance:product_journal_config:approve:1', payload);
export const fetchActivate = (payload: any = null): Promise<any> => rpcCall('urn:finance:product_journal_config:activate:1', payload);
export const fetchClose = (payload: any = null): Promise<any> => rpcCall('urn:finance:product_journal_config:close:1', payload);
