// ================================================
// WARNING: This file is automatically generated.
// Do not modify it by hand. Your changes will be
// overwritten the next time the generator runs.
// ================================================

import { rpcCall } from '../../../shared/RpcModels';

export const fetchList = (payload: any = null): Promise<any> => rpcCall('urn:finance:numbers:list:1', payload);
export const fetchGet = (payload: any = null): Promise<any> => rpcCall('urn:finance:numbers:get:1', payload);
export const fetchUpsert = (payload: any = null): Promise<any> => rpcCall('urn:finance:numbers:upsert:1', payload);
export const fetchDelete = (payload: any = null): Promise<any> => rpcCall('urn:finance:numbers:delete:1', payload);
export const fetchNextNumber = (payload: any = null): Promise<any> => rpcCall('urn:finance:numbers:next_number:1', payload);
export const fetchShift = (payload: any = null): Promise<any> => rpcCall('urn:finance:numbers:shift:1', payload);
