// ================================================
// WARNING: This file is automatically generated.
// Do not modify it by hand. Your changes will be
// overwritten the next time the generator runs.
// ================================================

import { rpcCall } from '../../../shared/RpcModels';

export const fetchProfile = (payload: any = null): Promise<any> => rpcCall('urn:admin:users:get_profile:1', payload);
export const fetchSetCredits = (payload: any = null): Promise<any> => rpcCall('urn:admin:users:set_credits:1', payload);
export const fetchResetDisplay = (payload: any = null): Promise<any> => rpcCall('urn:admin:users:reset_display:1', payload);
export const fetchEnableStorage = (payload: any = null): Promise<any> => rpcCall('urn:admin:users:enable_storage:1', payload);
