// ================================================
// WARNING: This file is automatically generated.
// Do not modify it by hand. Your changes will be
// overwritten the next time the generator runs.
// ================================================

import { rpcCall, AdminUserProfile1, AdminUserRoles1, AdminUsersList1 } from '../../../shared/RpcModels';

export const fetchList = (payload: any = null): Promise<AdminUsersList1> => rpcCall('urn:admin:users:list:1', payload);
export const fetchRoles = (payload: any = null): Promise<AdminUserRoles1> => rpcCall('urn:admin:users:get_roles:1', payload);
export const fetchSetRoles = (payload: any = null): Promise<AdminUserRoles1> => rpcCall('urn:admin:users:set_roles:1', payload);
export const fetchListRoles = (payload: any = null): Promise<AdminUserRoles1> => rpcCall('urn:admin:users:list_roles:1', payload);
export const fetchProfile = (payload: any = null): Promise<AdminUserProfile1> => rpcCall('urn:admin:users:get_profile:1', payload);
