// ================================================
// WARNING: This file is automatically generated.
// Do not modify it by hand. Your changes will be
// overwritten the next time the generator runs.
// ================================================

import { rpcCall } from '../../../shared/RpcModels';

export const fetchDelete = (payload: any = null): Promise<any> => rpcCall('urn:service:renewals:delete:1', payload);
export const fetchGet = (payload: any = null): Promise<any> => rpcCall('urn:service:renewals:get:1', payload);
export const fetchList = (payload: any = null): Promise<any> => rpcCall('urn:service:renewals:list:1', payload);
export const fetchUpsert = (payload: any = null): Promise<any> => rpcCall('urn:service:renewals:upsert:1', payload);
