// ================================================
// WARNING: This file is automatically generated.
// Do not modify it by hand. Your changes will be
// overwritten the next time the generator runs.
// ================================================

import { rpcCall } from '../../../shared/RpcModels';

export const fetchPersonas = (payload: any = null): Promise<any> => rpcCall('urn:discord:personas:get_personas:1', payload);
export const fetchModels = (payload: any = null): Promise<any> => rpcCall('urn:discord:personas:get_models:1', payload);
export const fetchUpsertPersona = (payload: any = null): Promise<any> => rpcCall('urn:discord:personas:upsert_persona:1', payload);
export const fetchDeletePersona = (payload: any = null): Promise<any> => rpcCall('urn:discord:personas:delete_persona:1', payload);
