// ================================================
// WARNING: This file is automatically generated.
// Do not modify it by hand. Your changes will be
// overwritten the next time the generator runs.
// ================================================

import { rpcCall } from '../../../shared/RpcModels';

export const fetchList = (payload: any = null): Promise<any> => rpcCall('urn:finance:periods:list:1', payload);
export const fetchListByYear = (payload: any = null): Promise<any> => rpcCall('urn:finance:periods:list_by_year:1', payload);
export const fetchGet = (payload: any = null): Promise<any> => rpcCall('urn:finance:periods:get:1', payload);
export const fetchClose = (payload: any = null): Promise<any> => rpcCall('urn:finance:periods:close:1', payload);
export const fetchReopen = (payload: any = null): Promise<any> => rpcCall('urn:finance:periods:reopen:1', payload);
export const fetchLock = (payload: any = null): Promise<any> => rpcCall('urn:finance:periods:lock:1', payload);
export const fetchUnlock = (payload: any = null): Promise<any> => rpcCall('urn:finance:periods:unlock:1', payload);
export const fetchListCloseBlockers = (payload: any = null): Promise<any> => rpcCall('urn:finance:periods:list_close_blockers:1', payload);
export const fetchUpsert = (payload: any = null): Promise<any> => rpcCall('urn:finance:periods:upsert:1', payload);
export const fetchDelete = (payload: any = null): Promise<any> => rpcCall('urn:finance:periods:delete:1', payload);
export const fetchGenerateCalendar = (payload: any = null): Promise<any> => rpcCall('urn:finance:periods:generate_calendar:1', payload);
