// ================================================
// WARNING: This file is automatically generated.
// Do not modify it by hand. Your changes will be
// overwritten the next time the generator runs.
// ================================================

import { rpcCall } from '../../../shared/RpcModels';

export const fetchListConversations = (payload: any = null): Promise<any> => rpcCall('urn:system:conversations:list_conversations:1', payload);
export const fetchStats = (payload: any = null): Promise<any> => rpcCall('urn:system:conversations:get_stats:1', payload);
export const fetchViewThread = (payload: any = null): Promise<any> => rpcCall('urn:system:conversations:view_thread:1', payload);
export const fetchDeleteThread = (payload: any = null): Promise<any> => rpcCall('urn:system:conversations:delete_thread:1', payload);
export const fetchDeleteBefore = (payload: any = null): Promise<any> => rpcCall('urn:system:conversations:delete_before:1', payload);
