// ================================================
// WARNING: This file is automatically generated.
// Do not modify it by hand. Your changes will be
// overwritten the next time the generator runs.
// ================================================

import { rpcCall } from '../../../shared/RpcModels';

export const fetchModels = (payload: any = null): Promise<any> => rpcCall('urn:system:models:get_models:1', payload);
export const fetchUpsertModel = (payload: any = null): Promise<any> => rpcCall('urn:system:models:upsert_model:1', payload);
export const fetchDeleteModel = (payload: any = null): Promise<any> => rpcCall('urn:system:models:delete_model:1', payload);
