// ================================================
// WARNING: This file is automatically generated.
// Do not modify it by hand. Your changes will be
// overwritten the next time the generator runs.
// ================================================

import { rpcCall } from '../../../shared/RpcModels';

export const fetchListByUser = (payload: any = null): Promise<any> => rpcCall('urn:finance:credit_lots:list_by_user:1', payload);
export const fetchGet = (payload: any = null): Promise<any> => rpcCall('urn:finance:credit_lots:get:1', payload);
export const fetchCreate = (payload: any = null): Promise<any> => rpcCall('urn:finance:credit_lots:create:1', payload);
export const fetchConsume = (payload: any = null): Promise<any> => rpcCall('urn:finance:credit_lots:consume:1', payload);
export const fetchExpire = (payload: any = null): Promise<any> => rpcCall('urn:finance:credit_lots:expire:1', payload);
export const fetchListEvents = (payload: any = null): Promise<any> => rpcCall('urn:finance:credit_lots:list_events:1', payload);
export const fetchWalletBalance = (payload: any = null): Promise<any> => rpcCall('urn:finance:credit_lots:wallet_balance:1', payload);
