// ================================================
// WARNING: This file is automatically generated.
// Do not modify it by hand. Your changes will be
// overwritten the next time the generator runs.
// ================================================

import { rpcCall } from '../../../shared/RpcModels';

export const fetchHomeLinks = (payload: any = null): Promise<any> => rpcCall('urn:public:links:get_home_links:1', payload);
export const fetchNavbarRoutes = (payload: any = null): Promise<any> => rpcCall('urn:public:links:get_navbar_routes:1', payload);
