// ================================================
// WARNING: This file is automatically generated.
// Do not modify it by hand. Your changes will be
// overwritten the next time the generator runs.
// ================================================

import { rpcCall } from '../../../shared/RpcModels';

export const fetchRoutes = (payload: any = null): Promise<any> => rpcCall('urn:system:routes:get_routes:1', payload);
export const fetchUpsertRoute = (payload: any = null): Promise<any> => rpcCall('urn:system:routes:upsert_route:1', payload);
export const fetchDeleteRoute = (payload: any = null): Promise<any> => rpcCall('urn:system:routes:delete_route:1', payload);
