// ================================================
// WARNING: This file is automatically generated.
// Do not modify it by hand. Your changes will be
// overwritten the next time the generator runs.
// ================================================

import { rpcCall, FrontendUserProfileData1 } from '../../../shared/RpcModels';

export const fetchProfileData = (payload: any = null): Promise<FrontendUserProfileData1> => rpcCall('urn:frontend:user:get_profile_data:1', payload);
export const fetchSetDisplayName = (payload: any = null): Promise<FrontendUserProfileData1> => rpcCall('urn:frontend:user:set_display_name:1', payload);
