// ================================================
// WARNING: This file is automatically generated.
// Do not modify it by hand. Your changes will be
// overwritten the next time the generator runs.
// ================================================

import axios from "axios";

export interface RPCRequest {
  op: string;
  payload: any | null;
  version: number;
  timestamp: string | null;
}
export interface RPCResponse {
  op: string;
  payload: any;
  version: number;
  timestamp: string | null;
}
export interface AuthMicrosoftOauthLogin1 {
  sessionToken: string;
  display_name: string;
  credits: number;
  profile_image: string | null;
}
export interface UsersProfileAuthProvider1 {
  name: string;
  display: string;
}
export interface UsersProfileProfile1 {
  guid: string;
  display_name: string;
  email: string;
  display_email: boolean;
  credits: number;
  profile_image: string | null;
  default_provider: string;
  auth_providers: UsersProfileAuthProvider1[];
}
export interface UsersProfileSetDisplay1 {
  display_name: string;
}
export interface UsersProfileSetOptin1 {
  display_email: boolean;
}
export interface UsersProvidersSetProvider1 {
  provider: string;
}
export interface PublicLinksHomeLinks1 {
  links: PublicLinksLinkItem1[];
}
export interface PublicLinksLinkItem1 {
  title: string;
  url: string;
}
export interface PublicLinksNavBarRoute1 {
  path: string;
  name: string;
  icon: string | null;
}
export interface PublicLinksNavBarRoutes1 {
  routes: PublicLinksNavBarRoute1[];
}
export interface PublicVarsFfmpegVersion1 {
  ffmpeg_version: string;
}
export interface PublicVarsHostname1 {
  hostname: string;
}
export interface PublicVarsOdbcVersion1 {
  odbc_version: string;
}
export interface PublicVarsRepo1 {
  repo: string;
}
export interface PublicVarsVersion1 {
  version: string;
}

export async function rpcCall<T>(op: string, payload: any = null): Promise<T> {
    const request: RPCRequest = {
        op,
        payload,
        version: 1,
        timestamp: new Date().toISOString()
    };
    const headers: Record<string, string> = {};
    if (typeof localStorage !== 'undefined') {
        try {
            const raw = localStorage.getItem('authTokens');
            if (raw) {
                const { sessionToken } = JSON.parse(raw);
                if (sessionToken) headers.Authorization = `Bearer ${sessionToken}`;
            }
        } catch {
            /* ignore token parsing errors */
        }
    }
    const response = await axios.post<RPCResponse>('/rpc', request, { headers });
    return response.data.payload as T;
}
