// ================================================
// WARNING: This file is automatically generated.
// Do not modify it by hand. Your changes will be
// overwritten the next time the generator runs.
// ================================================

import { rpcCall, SystemLinksHome1, SystemLinksRoutes1 } from '../../../shared/RpcModels';

export const fetchHome = (payload: any = null): Promise<SystemLinksHome1> => rpcCall('urn:system:links:get_home:1', payload);
export const fetchRoutes = (payload: any = null): Promise<SystemLinksRoutes1> => rpcCall('urn:system:links:get_routes:1', payload);
