// ================================================
// WARNING: This file is automatically generated.
// Do not modify it by hand. Your changes will be
// overwritten the next time the generator runs.
// ================================================

import axios from "axios";
import { getFingerprint } from "../shared/fingerprint";

export interface ConfigKeyParams {
	key: string;
}
export interface UpsertConfigParams {
	key: string;
	value: string;
}
export interface CreateSessionParams {
	access_token: string;
	expires: any;
	fingerprint: string;
	rotkey: string;
	rotkey_iat: any;
	rotkey_exp: any;
	user_guid: string;
	provider: string;
	user_agent: any;
	ip_address: any;
}
export interface GuidParams {
	guid: string;
}
export interface RevokeDeviceTokenParams {
	access_token: string;
}
export interface RevokeProviderTokensParams {
	guid: string;
	provider: string;
}
export interface RotkeyLookupParams {
	guid: string;
	device_guid: any;
	fingerprint: any;
}
export interface SetRotkeyParams {
	guid: string;
	rotkey: string;
	iat: any;
	exp: any;
	device_guid: any;
}
export interface UpdateDeviceTokenParams {
	device_guid: string;
	access_token: string;
}
export interface UpdateSessionParams {
	access_token: string;
	user_agent: any;
	ip_address: any;
}
export interface SetDisplayParams {
	guid: string;
	display_name: string;
}
export interface SetOptInParams {
	guid: string;
	display_email: boolean;
}
export interface SetProfileImageParams {
	guid: string;
	provider: string;
	image_b64: any;
}
export interface SetRolesParams {
	guid: string;
	roles: number;
}
export interface UpdateIfUneditedParams {
	guid: string;
	display_name: any;
	email: any;
}
export interface UpdateProfileParams {
	guid: string;
	display_name: any;
	display_email: any;
	provider: any;
	image_b64: any;
}

export async function dbCall<T>(op: string, payload: any = null): Promise<T> {
	const request = {
		op,
		payload: payload ?? {},
	};
	const headers: Record<string, string> = {};
	if (typeof localStorage !== 'undefined') {
		try {
			const raw = localStorage.getItem('authTokens');
			if (raw) {
				const { sessionToken } = JSON.parse(raw);
				if (sessionToken) headers.Authorization = `Bearer ${sessionToken}`;
			}
		} catch {
			/* ignore token parsing errors */
		}
	}
	try {
		const response = await axios.post('/db', request, { headers });
		return response.data.payload as T;
	} catch (err: any) {
		if (axios.isAxiosError(err) && err.response?.status === 401) {
			try {
				const refreshReq = {
					op: 'urn:auth:session:refresh_token:1',
					payload: { fingerprint: getFingerprint() },
					version: 1,
					timestamp: new Date().toISOString(),
				};
				const refreshResp = await axios.post('/rpc', refreshReq);
				const newToken = refreshResp.data.payload.token;
				if (typeof localStorage !== 'undefined') {
					const raw = localStorage.getItem('authTokens');
					if (raw) {
						const data = JSON.parse(raw);
						data.sessionToken = newToken;
						localStorage.setItem('authTokens', JSON.stringify(data));
					}
				}
				headers.Authorization = `Bearer ${newToken}`;
				const retryResp = await axios.post('/db', request, { headers });
				return retryResp.data.payload as T;
			} catch {
				if (typeof localStorage !== 'undefined') {
					localStorage.removeItem('authTokens');
				}
				if (typeof window !== 'undefined') {
					window.dispatchEvent(new Event('sessionExpired'));
				}
			}
		}
		throw err;
	}
}

export const dbFinanceStatusCheckStatus = (payload: any = null): Promise<any> => dbCall('db:finance:status:check_status:1', payload);
export const dbIdentityAccountsExists = (payload: any = null): Promise<any> => dbCall('db:identity:accounts:exists:1', payload);
export const dbIdentityAccountsRead = (payload: any = null): Promise<any> => dbCall('db:identity:accounts:read:1', payload);
export const dbIdentityProfilesRead = (payload: any = null): Promise<any> => dbCall('db:identity:profiles:read:1', payload);
export const dbIdentityProfilesUpdate = (payload: any = null): Promise<any> => dbCall('db:identity:profiles:update:1', payload);
export const dbIdentityProfilesUpdateIfUnedited = (payload: any = null): Promise<any> => dbCall('db:identity:profiles:update_if_unedited:1', payload);
export const dbIdentityProvidersCreateFromProvider = (payload: any = null): Promise<any> => dbCall('db:identity:providers:create_from_provider:1', payload);
export const dbIdentityProvidersGetAnyByProviderIdentifier = (payload: any = null): Promise<any> => dbCall('db:identity:providers:get_any_by_provider_identifier:1', payload);
export const dbIdentityProvidersGetByProviderIdentifier = (payload: any = null): Promise<any> => dbCall('db:identity:providers:get_by_provider_identifier:1', payload);
export const dbIdentityProvidersGetUserByEmail = (payload: any = null): Promise<any> => dbCall('db:identity:providers:get_user_by_email:1', payload);
export const dbIdentityProvidersLinkProvider = (payload: any = null): Promise<any> => dbCall('db:identity:providers:link_provider:1', payload);
export const dbIdentityProvidersRelink = (payload: any = null): Promise<any> => dbCall('db:identity:providers:relink:1', payload);
export const dbIdentityProvidersSetProvider = (payload: any = null): Promise<any> => dbCall('db:identity:providers:set_provider:1', payload);
export const dbIdentityProvidersSoftDeleteAccount = (payload: any = null): Promise<any> => dbCall('db:identity:providers:soft_delete_account:1', payload);
export const dbIdentityProvidersUnlinkLastProvider = (payload: any = null): Promise<any> => dbCall('db:identity:providers:unlink_last_provider:1', payload);
export const dbIdentityProvidersUnlinkProvider = (payload: any = null): Promise<any> => dbCall('db:identity:providers:unlink_provider:1', payload);
export const dbIdentityRoleMembershipsCreate = (payload: any = null): Promise<any> => dbCall('db:identity:role_memberships:create:1', payload);
export const dbIdentityRoleMembershipsDelete = (payload: any = null): Promise<any> => dbCall('db:identity:role_memberships:delete:1', payload);
export const dbIdentityRoleMembershipsList = (payload: any = null): Promise<any> => dbCall('db:identity:role_memberships:list:1', payload);
export const dbIdentityRoleMembershipsListNonMembers = (payload: any = null): Promise<any> => dbCall('db:identity:role_memberships:list_non_members:1', payload);
export const dbIdentitySessionsGetRotkey = (payload: any = null): Promise<any> => dbCall('db:identity:sessions:get_rotkey:1', payload);
export const dbIdentitySessionsRead = (payload: any = null): Promise<any> => dbCall('db:identity:sessions:read:1', payload);
export const dbSystemConfigurationCheckStatus = (payload: any = null): Promise<any> => dbCall('db:system:configuration:check_status:1', payload);
export const dbSystemLinksGetHomeLinks = (payload: any = null): Promise<any> => dbCall('db:system:links:get_home_links:1', payload);
export const dbSystemLinksGetNavbarRoutes = (payload: any = null): Promise<any> => dbCall('db:system:links:get_navbar_routes:1', payload);
export const dbSystemPublicVarsGetHostname = (payload: any = null): Promise<any> => dbCall('db:system:public_vars:get_hostname:1', payload);
export const dbSystemPublicVarsGetRepo = (payload: any = null): Promise<any> => dbCall('db:system:public_vars:get_repo:1', payload);
export const dbSystemPublicVarsGetVersion = (payload: any = null): Promise<any> => dbCall('db:system:public_vars:get_version:1', payload);
export const dbSystemRolesCreate = (payload: any = null): Promise<any> => dbCall('db:system:roles:create:1', payload);
export const dbSystemRolesDelete = (payload: any = null): Promise<any> => dbCall('db:system:roles:delete:1', payload);
export const dbSystemRolesList = (payload: any = null): Promise<any> => dbCall('db:system:roles:list:1', payload);
export const dbSystemRolesUpdate = (payload: any = null): Promise<any> => dbCall('db:system:roles:update:1', payload);
