// ================================================
// WARNING: This file is automatically generated.
// Do not modify it by hand. Your changes will be
// overwritten the next time the generator runs.
// ================================================

import axios from 'axios';
import { RPCRequest, RPCResponse } from '../../../shared/RpcModels';

const rpcCall = async <T>(op: string): Promise<T> => {
    const request: RPCRequest = {
        op,
        payload: null,
        version: 1,
        timestamp: Date.now(),
        metadata: null,
    };
    const response = await axios.post<RPCResponse>('/rpc', request);
    return response.data.payload as T;
};

export const fetchUserLogin = (): Promise<any> => rpcCall('urn:auth:microsoft:user_login:1');
