// ================================================
// WARNING: This file is automatically generated.
// Do not modify it by hand. Your changes will be
// overwritten the next time the generator runs.
// ================================================

import { rpcCall, AuthMicrosoftLoginData1 } from '../../../shared/RpcModels';

export const fetchUserLogin = (payload: any = null): Promise<AuthMicrosoftLoginData1> => rpcCall('urn:auth:microsoft:user_login:1', payload);
