// ================================================
// WARNING: This file is automatically generated.
// Do not modify it by hand. Your changes will be
// overwritten the next time the generator runs.
// ================================================

import { rpcCall } from '../../../shared/RpcModels';

export const fetchReviewContent = (payload: any = null): Promise<any> => rpcCall('urn:moderation:content:review_content:1', payload);
