// ================================================
// WARNING: This file is automatically generated.
// Do not modify it by hand. Your changes will be
// overwritten the next time the generator runs.
// ================================================

import { rpcCall } from '../../../shared/RpcModels';

export const fetchProfile = (payload: any = null): Promise<any> => rpcCall('urn:public:users:get_profile:1', payload);
export const fetchPublishedFiles = (payload: any = null): Promise<any> => rpcCall('urn:public:users:get_published_files:1', payload);
