// ================================================
// WARNING: This file is automatically generated.
// Do not modify it by hand. Your changes will be
// overwritten the next time the generator runs.
// ================================================

import { rpcCall } from '../../../shared/RpcModels';

export const fetchList = (payload: any = null): Promise<any> => rpcCall('urn:finance:dimensions:list:1', payload);
export const fetchListByName = (payload: any = null): Promise<any> => rpcCall('urn:finance:dimensions:list_by_name:1', payload);
export const fetchGet = (payload: any = null): Promise<any> => rpcCall('urn:finance:dimensions:get:1', payload);
export const fetchUpsert = (payload: any = null): Promise<any> => rpcCall('urn:finance:dimensions:upsert:1', payload);
export const fetchDelete = (payload: any = null): Promise<any> => rpcCall('urn:finance:dimensions:delete:1', payload);
