// ================================================
// WARNING: This file is automatically generated.
// Do not modify it by hand. Your changes will be
// overwritten the next time the generator runs.
// ================================================

import { rpcCall } from '../../../shared/RpcModels';

export const fetchListTables = (payload: any = null): Promise<any> => rpcCall('urn:service:reflection:list_tables:1', payload);
export const fetchDescribeTable = (payload: any = null): Promise<any> => rpcCall('urn:service:reflection:describe_table:1', payload);
export const fetchListViews = (payload: any = null): Promise<any> => rpcCall('urn:service:reflection:list_views:1', payload);
export const fetchFullSchema = (payload: any = null): Promise<any> => rpcCall('urn:service:reflection:get_full_schema:1', payload);
export const fetchSchemaVersion = (payload: any = null): Promise<any> => rpcCall('urn:service:reflection:get_schema_version:1', payload);
export const fetchDumpTable = (payload: any = null): Promise<any> => rpcCall('urn:service:reflection:dump_table:1', payload);
export const fetchQueryInfoSchema = (payload: any = null): Promise<any> => rpcCall('urn:service:reflection:query_info_schema:1', payload);
export const fetchListDomains = (payload: any = null): Promise<any> => rpcCall('urn:service:reflection:list_domains:1', payload);
export const fetchListRpcEndpoints = (payload: any = null): Promise<any> => rpcCall('urn:service:reflection:list_rpc_endpoints:1', payload);
