// ================================================
// WARNING: This file is automatically generated.
// Do not modify it by hand. Your changes will be
// overwritten the next time the generator runs.
// ================================================

import { rpcCall, AuthSessionTokens1 } from '../../../shared/RpcModels';

export const fetchRefresh = (payload: any = null): Promise<AuthSessionTokens1> => rpcCall('urn:auth:session:refresh:1', payload);
export const fetchInvalidate = (payload: any = null): Promise<any> => rpcCall('urn:auth:session:invalidate:1', payload);
