// ================================================
// WARNING: This file is automatically generated.
// Do not modify it by hand. Your changes will be
// overwritten the next time the generator runs.
// ================================================

import { rpcCall } from '../../../shared/RpcModels';

export const fetchList = (payload: any = null): Promise<any> => rpcCall('urn:finance:pipeline_config:list:1', payload);
export const fetchGet = (payload: any = null): Promise<any> => rpcCall('urn:finance:pipeline_config:get:1', payload);
export const fetchUpsert = (payload: any = null): Promise<any> => rpcCall('urn:finance:pipeline_config:upsert:1', payload);
export const fetchDelete = (payload: any = null): Promise<any> => rpcCall('urn:finance:pipeline_config:delete:1', payload);
