// ================================================
// WARNING: This file is automatically generated.
// Do not modify it by hand. Your changes will be
// overwritten the next time the generator runs.
// ================================================

import { rpcCall } from '../../../shared/RpcModels';

export const fetchProfile = (payload: any = null): Promise<any> => rpcCall('urn:users:profile:get_profile:1', payload);
export const fetchSetDisplay = (payload: any = null): Promise<any> => rpcCall('urn:users:profile:set_display:1', payload);
export const fetchSetOptin = (payload: any = null): Promise<any> => rpcCall('urn:users:profile:set_optin:1', payload);
export const fetchRoles = (payload: any = null): Promise<any> => rpcCall('urn:users:profile:get_roles:1', payload);
export const fetchSetRoles = (payload: any = null): Promise<any> => rpcCall('urn:users:profile:set_roles:1', payload);
export const fetchSetProfileImage = (payload: any = null): Promise<any> => rpcCall('urn:users:profile:set_profile_image:1', payload);
