// ================================================
// WARNING: This file is automatically generated.
// Do not modify it by hand. Your changes will be
// overwritten the next time the generator runs.
// ================================================

import { rpcCall, AdminRoutesList1 } from '../../../shared/RpcModels';

export const fetchList = (payload: any = null): Promise<AdminRoutesList1> => rpcCall('urn:admin:routes:list:1', payload);
export const fetchSet = (payload: any = null): Promise<any> => rpcCall('urn:admin:routes:set:1', payload);
export const fetchDelete = (payload: any = null): Promise<any> => rpcCall('urn:admin:routes:delete:1', payload);
