// ================================================
// WARNING: This file is automatically generated.
// Do not modify it by hand. Your changes will be
// overwritten the next time the generator runs.
// ================================================

import { rpcCall } from '../../../shared/RpcModels';

export const fetchListGuilds = (payload: any = null): Promise<any> => rpcCall('urn:discord:guilds:list_guilds:1', payload);
export const fetchGuild = (payload: any = null): Promise<any> => rpcCall('urn:discord:guilds:get_guild:1', payload);
export const fetchUpdateCredits = (payload: any = null): Promise<any> => rpcCall('urn:discord:guilds:update_credits:1', payload);
export const fetchSyncGuilds = (payload: any = null): Promise<any> => rpcCall('urn:discord:guilds:sync_guilds:1', payload);
