// ================================================
// WARNING: This file is automatically generated.
// Do not modify it by hand. Your changes will be
// overwritten the next time the generator runs.
// ================================================

import { rpcCall } from '../../../shared/RpcModels';

export const fetchOauthLogin = (payload: any = null): Promise<any> => rpcCall('urn:auth:google:oauth_login:1', payload);
