// ================================================
// WARNING: This file is automatically generated.
// Do not modify it by hand. Your changes will be
// overwritten the next time the generator runs.
// ================================================

import { rpcCall, AuthGoogleLoginData1 } from '../../../shared/RpcModels';

export const fetchUserLogin = (payload: any = null): Promise<AuthGoogleLoginData1> => rpcCall('urn:auth:google:user_login:1', payload);
