// ================================================
// WARNING: This file is automatically generated.
// Do not modify it by hand. Your changes will be
// overwritten the next time the generator runs.
// ================================================

import { rpcCall, AccountUserProfile1, AccountUserRoles1, AccountUsersList1 } from '../../../shared/RpcModels';

export const fetchList = (payload: any = null): Promise<AccountUsersList1> => rpcCall('urn:account:users:list:1', payload);
export const fetchRoles = (payload: any = null): Promise<AccountUserRoles1> => rpcCall('urn:account:users:get_roles:1', payload);
export const fetchSetRoles = (payload: any = null): Promise<AccountUserRoles1> => rpcCall('urn:account:users:set_roles:1', payload);
export const fetchListRoles = (payload: any = null): Promise<AccountUserRoles1> => rpcCall('urn:account:users:list_roles:1', payload);
export const fetchProfile = (payload: any = null): Promise<AccountUserProfile1> => rpcCall('urn:account:users:get_profile:1', payload);
export const fetchSetCredits = (payload: any = null): Promise<AccountUserProfile1> => rpcCall('urn:account:users:set_credits:1', payload);
export const fetchEnableStorage = (payload: any = null): Promise<AccountUserProfile1> => rpcCall('urn:account:users:enable_storage:1', payload);
