// ================================================
// WARNING: This file is automatically generated.
// Do not modify it by hand. Your changes will be
// overwritten the next time the generator runs.
// ================================================

import { rpcCall } from '../../../shared/RpcModels';

export const fetchList = (payload: any = null): Promise<any> => rpcCall('urn:system:tasks:list:1', payload);
export const fetchGet = (payload: any = null): Promise<any> => rpcCall('urn:system:tasks:get:1', payload);
export const fetchSubmit = (payload: any = null): Promise<any> => rpcCall('urn:system:tasks:submit:1', payload);
export const fetchCancel = (payload: any = null): Promise<any> => rpcCall('urn:system:tasks:cancel:1', payload);
export const fetchRetry = (payload: any = null): Promise<any> => rpcCall('urn:system:tasks:retry:1', payload);
export const fetchEvents = (payload: any = null): Promise<any> => rpcCall('urn:system:tasks:events:1', payload);
