// ================================================
// WARNING: This file is automatically generated.
// Do not modify it by hand. Your changes will be
// overwritten the next time the generator runs.
// ================================================

import { rpcCall } from '../../../shared/RpcModels';

export const fetchSetProvider = (payload: any = null): Promise<any> => rpcCall('urn:users:providers:set_provider:1', payload);
export const fetchLinkProvider = (payload: any = null): Promise<any> => rpcCall('urn:users:providers:link_provider:1', payload);
export const fetchUnlinkProvider = (payload: any = null): Promise<any> => rpcCall('urn:users:providers:unlink_provider:1', payload);
export const fetchByProviderIdentifier = (payload: any = null): Promise<any> => rpcCall('urn:users:providers:get_by_provider_identifier:1', payload);
export const fetchCreateFromProvider = (payload: any = null): Promise<any> => rpcCall('urn:users:providers:create_from_provider:1', payload);
