// ================================================
// WARNING: This file is automatically generated.
// Do not modify it by hand. Your changes will be
// overwritten the next time the generator runs.
// ================================================

import { rpcCall } from '../../../shared/RpcModels';

export const fetchRoles = (payload: any = null): Promise<any> => rpcCall('urn:discord:command:get_roles:1', payload);
export const fetchRegister = (payload: any = null): Promise<any> => rpcCall('urn:discord:command:register:1', payload);
export const fetchCredits = (payload: any = null): Promise<any> => rpcCall('urn:discord:command:get_credits:1', payload);
export const fetchGuildCredits = (payload: any = null): Promise<any> => rpcCall('urn:discord:command:get_guild_credits:1', payload);
