from __future__ import annotations

import ast
import importlib.util
import inspect
import os
import types
import uuid
from datetime import datetime
from typing import Any, Union, get_args, get_origin

from pydantic import BaseModel

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
RPC_REFLECTION_NAMESPACE = uuid.UUID("a1b2c3d4-e5f6-7890-abcd-ef1234567890")

PY_TO_TS = {
  str: "string",
  int: "number",
  float: "number",
  bool: "boolean",
  type(None): "null",
  dict: "Record<string, any>",
  datetime: "string",
  list: "any[]",
}

HEADER_COMMENT = [
  "// ================================================",
  "// WARNING: This file is automatically generated.",
  "// Do not modify it by hand. Your changes will be",
  "// overwritten the next time the generator runs.",
  "// ================================================",
  "",
]


def camel_case(name: str) -> str:
  return "".join(part.capitalize() for part in name.split("_"))


def load_module(path: str) -> types.ModuleType:
  module_name = os.path.splitext(os.path.basename(path))[0] + "_tmp"
  spec = importlib.util.spec_from_file_location(module_name, path)
  if not spec or not spec.loader:
    raise ImportError(f"Could not load spec for module at {path}")
  module = importlib.util.module_from_spec(spec)
  spec.loader.exec_module(module)
  return module


def parse_dispatchers(path: str) -> tuple[list[str], list[dict[str, str]]]:
  with open(path, 'r') as f:
    tree = ast.parse(f.read(), filename=path)

  operations: list[dict[str, str]] = []
  for node in tree.body:
    if isinstance(node, ast.Assign):
      targets = [t.id for t in node.targets if isinstance(t, ast.Name)]
      value = node.value
    elif isinstance(node, ast.AnnAssign):
      targets = [node.target.id] if isinstance(node.target, ast.Name) else []
      value = node.value
    else:
      continue
    if 'DISPATCHERS' in targets and isinstance(value, ast.Dict):
      for key, val in zip(value.keys, value.values):
        if not (isinstance(key, ast.Tuple) and len(key.elts) == 2):
          continue
        k0, k1 = key.elts
        if not (isinstance(k0, ast.Constant) and isinstance(k1, ast.Constant)):
          continue
        op, ver = k0.value, k1.value
        if isinstance(val, ast.Name):
          func = val.id
          operations.append({'op': op, 'version': ver, 'func': func})
  rel_dir = os.path.relpath(os.path.dirname(path), os.path.join(REPO_ROOT, 'rpc'))
  parts = [] if rel_dir == '.' else rel_dir.split(os.sep)
  return parts, operations


def _annotation_to_str(node: ast.AST) -> str:
  if isinstance(node, ast.Name):
    return node.id
  if isinstance(node, ast.Attribute):
    return node.attr
  if isinstance(node, ast.Subscript):
    return _annotation_to_str(node.slice)
  if isinstance(node, ast.Index):  # type: ignore[attr-defined]
    return _annotation_to_str(node.value)
  if isinstance(node, ast.Constant):
    return str(node.value)
  return 'any'


def parse_service_models(path: str) -> dict[str, str]:
  models: dict[str, str] = {}
  if not os.path.exists(path):
    return models
  with open(path, 'r') as f:
    tree = ast.parse(f.read(), filename=path)
  for node in tree.body:
    if isinstance(node, ast.AsyncFunctionDef):
      defaults = [None] * (len(node.args.args) - len(node.args.defaults)) + node.args.defaults
      for arg, _default in zip(node.args.args, defaults):
        if arg.arg != 'payload':
          continue
        if arg.annotation is None:
          continue
        model = _annotation_to_str(arg.annotation)
        models[node.name] = model
  return models




def _call_name(node: ast.Call) -> str | None:
  if isinstance(node.func, ast.Name):
    return node.func.id
  if isinstance(node.func, ast.Attribute):
    return node.func.attr
  return None


def _is_payload_expr(node: ast.AST) -> bool:
  if isinstance(node, ast.Attribute):
    return node.attr == 'payload'
  if isinstance(node, ast.BoolOp) and isinstance(node.op, ast.Or):
    return any(_is_payload_expr(value) for value in node.values)
  return False


def _extract_input_model(call: ast.Call) -> str | None:
  for kw in call.keywords:
    if kw.arg is None and _is_payload_expr(kw.value):
      return _call_name(call)

  if (
    isinstance(call.func, ast.Attribute)
    and call.func.attr == 'model_validate'
    and call.args
    and _is_payload_expr(call.args[0])
  ):
    model_node = call.func.value
    if isinstance(model_node, ast.Name):
      return model_node.id
    if isinstance(model_node, ast.Attribute):
      return model_node.attr
  return None


def _find_response_payload_var(func_body: list[ast.stmt]) -> str | None:
  for stmt in func_body:
    if not isinstance(stmt, ast.Return) or not isinstance(stmt.value, ast.Call):
      continue
    call = stmt.value
    if _call_name(call) != 'RPCResponse':
      continue
    for kw in call.keywords:
      if kw.arg != 'payload':
        continue
      if (
        isinstance(kw.value, ast.Call)
        and isinstance(kw.value.func, ast.Attribute)
        and kw.value.func.attr == 'model_dump'
      ):
        payload_value = kw.value.func.value
        if isinstance(payload_value, ast.Name):
          return payload_value.id
      return None
  return None


def parse_service_contracts(path: str) -> dict[str, dict[str, str | None]]:
  contracts: dict[str, dict[str, str | None]] = {}
  if not os.path.exists(path):
    return contracts

  with open(path, 'r') as f:
    tree = ast.parse(f.read(), filename=path)

  for node in tree.body:
    if not isinstance(node, ast.AsyncFunctionDef):
      continue

    input_model: str | None = None
    output_model: str | None = None
    var_models: dict[str, str] = {}

    for stmt in ast.walk(node):
      if isinstance(stmt, ast.Assign) and len(stmt.targets) == 1:
        target = stmt.targets[0]
        value = stmt.value
      elif isinstance(stmt, ast.AnnAssign) and stmt.value is not None:
        target = stmt.target
        value = stmt.value
      else:
        continue

      if not isinstance(target, ast.Name) or not isinstance(value, ast.Call):
        continue

      model_name = _call_name(value)
      if model_name and model_name[:1].isupper():
        var_models[target.id] = model_name

      detected_input = _extract_input_model(value)
      if detected_input and detected_input[:1].isupper():
        input_model = detected_input

    response_var = _find_response_payload_var(node.body)
    if response_var and response_var in var_models:
      output_model = var_models[response_var]

    contracts[node.name] = {'input': input_model, 'output': output_model}

  return contracts
def find_all_model_classes(rpc_root: str) -> list[tuple[str, type[BaseModel], str, str]]:
  model_classes: list[tuple[str, type[BaseModel], str, str]] = []
  seen: set[str] = set()
  for root, _, files in os.walk(rpc_root):
    if 'models.py' not in files:
      continue
    models_path = os.path.join(root, 'models.py')
    try:
      module = load_module(models_path)
    except Exception:
      continue

    rel_path = os.path.relpath(models_path, rpc_root)
    parts = rel_path.split(os.sep)
    domain = parts[0] if len(parts) > 1 else ""
    subdomain = parts[1] if len(parts) > 2 else ""

    for _, obj in inspect.getmembers(module):
      if inspect.isclass(obj) and issubclass(obj, BaseModel) and obj is not BaseModel:
        if obj.__name__ in {'RPCRequest', 'RPCResponse'}:
          continue
        if obj.__module__ != module.__name__:
          continue
        if obj.__name__ in seen:
          continue
        seen.add(obj.__name__)
        model_classes.append((obj.__name__, obj, domain, subdomain))

  return model_classes


def _py_to_ts(py_type: Any) -> str:
  origin = get_origin(py_type)
  args = get_args(py_type)
  if origin in (list, tuple):
    inner_type = _py_to_ts(args[0]) if args else "any"
    return f"{inner_type}[]"
  if origin is Union:
    non_none = [arg for arg in args if arg is not type(None)]
    if len(non_none) == 1:
      return f"{_py_to_ts(non_none[0])} | null"
    return " | ".join(_py_to_ts(arg) for arg in args)
  if py_type in PY_TO_TS:
    return PY_TO_TS[py_type]
  if isinstance(py_type, type) and issubclass(py_type, BaseModel):
    return py_type.__name__
  return "any"


def model_to_ts(model: type[BaseModel]) -> str:
  fields = getattr(model, "model_fields", None) or getattr(model, "__fields__", {})
  if not fields:
    return f"export type {model.__name__} = Record<string, never>;"
  lines = [f"export interface {model.__name__} {{"]
  for name, field in fields.items():
    annotation = getattr(field, "annotation", None) or getattr(field, "outer_type_", None)
    ts_type = _py_to_ts(annotation)
    lines.append(f"  {name}: {ts_type};")
  lines.append("}")
  return "\n".join(lines)
