from __future__ import annotations

import importlib.util
import json
import logging
import os
import re
import types
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Union, get_args, get_origin

import dotenv
from pydantic import BaseModel


logger = logging.getLogger(__name__)


dotenv.load_dotenv()


def select_environment(environment: str) -> None:
  """Configure environment variables for the requested execution environment."""
  env = environment.lower()
  logger.debug('Selecting environment %s', env)
  if env not in {'prod', 'test'}:
    raise ValueError("environment must be 'prod' or 'test'")
  suffix = '' if env == 'prod' else '_DEV'
  overrides = {
    'AZURE_SQL_CONNECTION_STRING': f'AZURE_SQL_CONNECTION_STRING{suffix}',
    'DISCORD_SECRET': f'DISCORD_SECRET{suffix}',
  }
  for target, source in overrides.items():
    value = os.getenv(source)
    if not value:
      raise RuntimeError(f"Environment variable {source} not set for {env} environment")
    os.environ[target] = value
    logger.debug('Set override %s from %s', target, source)

# Root of the repository relative to this file
REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))

# Root of the solution using Pathlib
ROOT = Path(__file__).resolve().parent.parent

# Map bare Python types to TS primitives (won't be used for generic types)
PY_TO_TS = {
  str: 'string',
  int: 'number',
  float: 'number',
  bool: 'boolean',
  type(None): 'null',
  dict: 'Record<string, any>',
  datetime: 'string',
  list: 'any[]',  # fallback for untyped list
}

# Standard header included at the top of generated files
HEADER_COMMENT = [
  '// ================================================',
  '// WARNING: This file is automatically generated.',
  '// Do not modify it by hand. Your changes will be',
  '// overwritten the next time the generator runs.',
  '// ================================================',
  '',
]


def camel_case(name: str) -> str:
  """Convert snake_case names to CamelCase."""
  return ''.join(part.capitalize() for part in name.split('_'))


def load_module(path: str) -> types.ModuleType:
  logger.debug('Loading module from path %s', path)
  module_name = os.path.splitext(os.path.basename(path))[0] + '_tmp'
  spec = importlib.util.spec_from_file_location(module_name, path)
  if not spec or not spec.loader:
    raise ImportError(f'Could not load spec for module at {path}')
  module = importlib.util.module_from_spec(spec)
  spec.loader.exec_module(module)
  logger.debug('Module %s loaded successfully', module_name)
  return module


def py_to_ts(py_type: Any) -> str:
  origin = get_origin(py_type)
  args = get_args(py_type)
  logger.debug('py_to_ts resolving type=%r origin=%r args=%r', py_type, origin, args)

  # Handle generics: List[X] or Tuple[X, ...]
  if origin in (list, tuple):
    inner_type = py_to_ts(args[0]) if args else 'any'
    result = f'{inner_type}[]'
    logger.debug('py_to_ts mapped list/tuple %r to %s', py_type, result)
    return result

  # Handle Optional[X] (i.e. Union[X, None])
  if origin is Union:
    non_none = [arg for arg in args if arg is not type(None)]
    if len(non_none) == 1:
      result = f'{py_to_ts(non_none[0])} | null'
      logger.debug('py_to_ts mapped optional %r to %s', py_type, result)
      return result
    result = ' | '.join(py_to_ts(arg) for arg in args)
    logger.debug('py_to_ts mapped union %r to %s', py_type, result)
    return result

  # Known primitives
  if py_type in PY_TO_TS:
    result = PY_TO_TS[py_type]
    logger.debug('py_to_ts used primitive map for %r -> %s', py_type, result)
    return result

  # Pydantic models → use interface name
  if isinstance(py_type, type) and issubclass(py_type, BaseModel):
    result = py_type.__name__
    logger.debug('py_to_ts resolved BaseModel %r -> %s', py_type, result)
    return result

  # Fallback
  logger.debug('py_to_ts falling back to any for %r', py_type)
  return 'any'


def model_to_ts(model: type[BaseModel]) -> str:
  logger.debug('Generating TypeScript interface for model %s', model.__name__)
  lines = [f'export interface {model.__name__} {{']
  fields = getattr(model, 'model_fields', None) or getattr(model, '__fields__', {})
  for name, field in fields.items():
    annotation = getattr(field, 'annotation', None) or getattr(field, 'outer_type_', None)
    ts_type = py_to_ts(annotation)
    logger.debug('Field %s annotated with %r mapped to %s', name, annotation, ts_type)
    lines.append(f'  {name}: {ts_type};')
  lines.append('}')
  logger.debug('Completed interface for %s with %d fields', model.__name__, len(fields))
  return '\n'.join(lines)


def parse_version(ver: str) -> tuple[int, int, int, int]:
  """Convert a version string like 'v1.2.3.4' into its numeric parts."""
  ver = ver.lstrip('v')
  major, minor, patch, build = [int(p) for p in ver.split('.')]
  logger.debug('Parsed version %s -> (%d, %d, %d, %d)', ver, major, minor, patch, build)
  return major, minor, patch, build


def next_build(current_version: str, last_version: str) -> int:
  """Return the next build number for the given versions.

  When the major or minor component changes the build counter resets to 0.
  Otherwise the counter is incremented from the current value.
  """
  cur_major, cur_minor, _, cur_build = parse_version(current_version)
  last_major, last_minor, _, _ = parse_version(last_version)
  if (cur_major, cur_minor) != (last_major, last_minor):
    return 0
  return cur_build + 1


def bump_version(version: str, part: str) -> str:
  """Increment the specified part of a version string."""
  ma, mi, pa, bu = parse_version(version)
  match part:
    case 'major':
      ma += 1
      mi = 0
      pa = 0
      bu = 0
    case 'minor':
      mi += 1
      pa = 0
      bu = 0
    case 'patch':
      pa += 1
      bu = 0
    case 'build':
      bu += 1
    case _:
      raise ValueError(f'Unknown part: {part}')
  new_version = f'v{ma}.{mi}.{pa}.{bu}'
  logger.debug('Bumped version %s part %s -> %s', version, part, new_version)
  return new_version


async def _fetch_json(cur):
  parts: list[str] = []
  while True:
    row = await cur.fetchone()
    if not row:
      break
    parts.append(row[0])
  result = json.loads(''.join(parts)) if parts else []
  logger.debug('_fetch_json assembled %d chunks into %d records', len(parts), len(result))
  return result


async def _fetch_dicts(cur):
  rows = await cur.fetchall()
  if not rows:
    logger.debug('_fetch_dicts returned 0 rows')
    return []
  cols = [d[0] for d in cur.description]
  result = [dict(zip(cols, row)) for row in rows]
  logger.debug('_fetch_dicts returning %d rows with columns %s', len(result), cols)
  return result


def _decode_optional(value):
  if value is None:
    return None
  logger.debug('_decode_optional processing value of type %s', type(value).__name__)
  if isinstance(value, memoryview):
    value = value.tobytes()
  if isinstance(value, (bytes, bytearray)):
    return value.decode('utf-16le')
  return value


def _quote(name: str) -> str:
  return '[' + name.replace(']', ']]') + ']'


def _qualify(schema: str, name: str) -> str:
  return f'{_quote(schema)}.{_quote(name)}'


def _map_constraint_type(code: str | None) -> str | None:
  if not code:
    return code
  mapping = {
    'PK': 'PRIMARY KEY',
    'UQ': 'UNIQUE',
    'F': 'FOREIGN KEY',
  }
  return mapping.get(code, code)


async def list_tables(conn):
  async with conn.cursor() as cur:
    await cur.execute(
      "SELECT TABLE_SCHEMA AS table_schema, TABLE_NAME AS table_name "
      "FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE='BASE TABLE' FOR JSON PATH"
    )
    result = await _fetch_json(cur)
  logger.debug('list_tables discovered %d tables', len(result))
  return result


async def list_views(conn):
  async with conn.cursor() as cur:
    await cur.execute(
      """SELECT CAST(SCHEMA_NAME(v.schema_id) AS NVARCHAR(4000)) AS view_schema,
                CAST(v.name AS NVARCHAR(4000)) AS view_name,
                CAST(m.definition AS NVARCHAR(4000)) AS view_definition
           FROM sys.views v
           JOIN sys.sql_modules m ON v.object_id = m.object_id
          WHERE SCHEMA_NAME(v.schema_id)='dbo'
           FOR JSON PATH"""
    )
    rows = await _fetch_dicts(cur)
  for row in rows:
    row['view_definition'] = _decode_optional(row['view_definition'])
  logger.debug('list_views retrieved %d views', len(rows))
  return rows


async def list_view_dependencies(conn):
  async with conn.cursor() as cur:
    await cur.execute(
      """SELECT CAST(OBJECT_NAME(d.referencing_id) AS NVARCHAR(4000)) AS view_name,
                CAST(OBJECT_NAME(d.referenced_id) AS NVARCHAR(4000)) AS ref_name
           FROM sys.sql_expression_dependencies d
           JOIN sys.views v ON d.referencing_id = v.object_id
           JOIN sys.views r ON d.referenced_id = r.object_id
          WHERE SCHEMA_NAME(v.schema_id)='dbo'
            AND SCHEMA_NAME(r.schema_id)='dbo'
           FOR JSON PATH"""
    )
    result = await _fetch_json(cur)
  logger.debug('list_view_dependencies found %d dependency records', len(result))
  return result


async def list_columns(conn, schema: str, table: str):
  async with conn.cursor() as cur:
    await cur.execute(
      """SELECT CAST(c.name AS NVARCHAR(4000)) AS column_name,
                CAST(t.name AS NVARCHAR(4000)) AS data_type,
                c.max_length,
                c.precision,
                c.scale,
                c.is_nullable,
                CAST(dc.definition AS NVARCHAR(4000)) AS default_definition,
                ic.seed_value,
                ic.increment_value,
                c.is_identity,
                c.is_rowguidcol,
                CAST(cc.definition AS NVARCHAR(4000)) AS computed_definition,
                cc.is_persisted,
                CAST(c.collation_name AS NVARCHAR(4000)) AS collation_name
           FROM sys.columns c
           JOIN sys.types t
             ON c.user_type_id = t.user_type_id
          LEFT JOIN sys.default_constraints dc
             ON c.default_object_id = dc.object_id
          LEFT JOIN sys.identity_columns ic
             ON c.object_id = ic.object_id AND c.column_id = ic.column_id
          LEFT JOIN sys.computed_columns cc
             ON c.object_id = cc.object_id AND c.column_id = cc.column_id
          WHERE c.object_id = OBJECT_ID(?)
          ORDER BY c.column_id""",
      (_qualify(schema, table),),
    )
  rows = await _fetch_dicts(cur)
  columns: list[dict] = []
  for row in rows:
    logger.debug(
      'Column %s.%s.%s type=%s max_length=%s precision=%s scale=%s nullable=%s',
      schema,
      table,
      row['column_name'],
      row['data_type'],
      row['max_length'],
      row['precision'],
      row['scale'],
      row['is_nullable'],
    )
    columns.append(
      {
        'name': row['column_name'],
        'data_type': row['data_type'],
        'max_length': row['max_length'],
        'precision': row['precision'],
        'scale': row['scale'],
        'nullable': bool(row['is_nullable']),
        'default': _decode_optional(row['default_definition']),
        'identity': bool(row['is_identity']),
        'identity_seed': row['seed_value'],
        'identity_increment': row['increment_value'],
        'rowguidcol': bool(row['is_rowguidcol']),
        'computed': _decode_optional(row['computed_definition']),
        'computed_persisted': bool(row['is_persisted']),
        'collation': row['collation_name'],
      }
    )
  logger.debug('list_columns returning %d columns for %s.%s', len(columns), schema, table)
  return columns


async def list_primary_key(conn, schema: str, table: str):
  async with conn.cursor() as cur:
    await cur.execute(
      """SELECT CAST(c.name AS NVARCHAR(4000)) AS column_name
           FROM sys.index_columns ic
           JOIN sys.columns c ON ic.object_id = c.object_id AND ic.column_id = c.column_id
           JOIN sys.indexes i ON ic.object_id = i.object_id AND ic.index_id = i.index_id
          WHERE i.object_id = OBJECT_ID(?) AND i.is_primary_key = 1
          ORDER BY ic.key_ordinal""",
      (_qualify(schema, table),),
    )
    rows = await _fetch_dicts(cur)
  result = [row['column_name'] for row in rows]
  logger.debug('list_primary_key for %s.%s -> %s', schema, table, result)
  return result


async def list_foreign_keys(conn, schema: str, table: str):
  async with conn.cursor() as cur:
    await cur.execute(
      """SELECT CAST(fk.name AS NVARCHAR(4000)) AS constraint_name,
                CAST(COL_NAME(fkc.parent_object_id, fkc.parent_column_id) AS NVARCHAR(4000)) AS column_name,
                CAST(OBJECT_SCHEMA_NAME(fkc.referenced_object_id) AS NVARCHAR(4000)) AS ref_schema,
                CAST(OBJECT_NAME(fkc.referenced_object_id) AS NVARCHAR(4000)) AS ref_table,
                CAST(COL_NAME(fkc.referenced_object_id, fkc.referenced_column_id) AS NVARCHAR(4000)) AS ref_column
           FROM sys.foreign_key_columns fkc
           JOIN sys.foreign_keys fk ON fkc.constraint_object_id = fk.object_id
          WHERE fkc.parent_object_id = OBJECT_ID(?)
          ORDER BY fk.name, fkc.constraint_column_id""",
      (_qualify(schema, table),),
    )
    rows = await _fetch_dicts(cur)
  grouped: dict[str, dict] = {}
  for row in rows:
    entry = grouped.setdefault(
      row['constraint_name'],
      {
        'name': row['constraint_name'],
        'columns': [],
        'ref_columns': [],
        'ref_schema': row['ref_schema'],
        'ref_table': row['ref_table'],
      },
    )
    entry['columns'].append(row['column_name'])
    entry['ref_columns'].append(row['ref_column'])
  result = list(grouped.values())
  logger.debug('list_foreign_keys for %s.%s -> %d constraints', schema, table, len(result))
  return result


async def list_indexes(conn, schema: str, table: str):
  async with conn.cursor() as cur:
    await cur.execute(
      """SELECT CAST(i.name AS NVARCHAR(4000)) AS index_name,
                i.is_unique AS is_unique,
                CAST(i.filter_definition AS NVARCHAR(4000)) AS filter_definition,
                ic.is_descending_key AS is_descending,
                ic.is_included_column AS is_included,
                ic.key_ordinal AS key_ordinal,
                ic.index_column_id AS index_column_id,
                CAST(c.name AS NVARCHAR(4000)) AS column_name
           FROM sys.indexes i
           JOIN sys.index_columns ic
             ON i.object_id = ic.object_id AND i.index_id = ic.index_id
           JOIN sys.columns c
             ON ic.object_id = c.object_id AND ic.column_id = c.column_id
          WHERE i.object_id = OBJECT_ID(?)
            AND i.is_primary_key = 0
            AND i.is_unique_constraint = 0
            AND i.type <> 0
            AND i.is_hypothetical = 0
            AND i.name IS NOT NULL
          ORDER BY i.name,
                   CASE WHEN ic.is_included_column = 0 THEN ic.key_ordinal ELSE ic.index_column_id END""",
      (_qualify(schema, table),),
    )
    rows = await _fetch_dicts(cur)
  indexes: dict[str, dict] = {}
  for row in rows:
    entry = indexes.setdefault(
      row['index_name'],
      {
        'index_name': row['index_name'],
        'is_unique': bool(row['is_unique']),
        'filter_definition': _decode_optional(row['filter_definition']),
        'columns': [],
      },
    )
    entry['columns'].append(
      {
        'column_name': row['column_name'],
        'is_descending': bool(row['is_descending']),
        'is_included': bool(row['is_included']),
      }
    )
  result = list(indexes.values())
  logger.debug('list_indexes for %s.%s -> %d indexes', schema, table, len(result))
  return result


async def list_constraints(conn, schema: str, table: str):
  async with conn.cursor() as cur:
    await cur.execute(
      """SELECT CAST(kc.name AS NVARCHAR(4000)) AS constraint_name,
                CAST(kc.type AS NVARCHAR(4000)) AS constraint_type,
                ic.key_ordinal,
                CAST(c.name AS NVARCHAR(4000)) AS column_name
           FROM sys.key_constraints kc
           JOIN sys.tables t ON kc.parent_object_id = t.object_id
           JOIN sys.schemas s ON t.schema_id = s.schema_id
           LEFT JOIN sys.index_columns ic
             ON kc.parent_object_id = ic.object_id
            AND kc.unique_index_id = ic.index_id
           LEFT JOIN sys.columns c
             ON ic.object_id = c.object_id
            AND ic.column_id = c.column_id
          WHERE s.name=? AND t.name=?
          ORDER BY kc.name, ic.key_ordinal""",
      (schema, table),
    )
    rows = await _fetch_dicts(cur)
  grouped: dict[str, dict] = {}
  order: list[str] = []
  for row in rows:
    name = row['constraint_name']
    if name not in grouped:
      order.append(name)
      grouped[name] = {
        'constraint_name': name,
        'constraint_type': _map_constraint_type(row['constraint_type']),
        'columns': [],
      }
    column = row.get('column_name')
    if column:
      grouped[name]['columns'].append(column)
  results: list[dict] = []
  for name in order:
    entry = grouped[name]
    columns = entry['columns']
    entry['columns'] = ', '.join(columns) if columns else None
    results.append(entry)
  logger.debug('list_constraints for %s.%s -> %d constraints', schema, table, len(results))
  return results


async def list_check_constraints(conn, schema: str, table: str):
  async with conn.cursor() as cur:
    await cur.execute(
      """SELECT CAST(cc.CONSTRAINT_NAME AS NVARCHAR(4000)) AS constraint_name,
                CAST(cc.definition AS NVARCHAR(4000)) AS definition,
                cc.is_not_trusted,
                cc.is_disabled
           FROM sys.check_constraints cc
          WHERE cc.parent_object_id = OBJECT_ID(?)""",
      (_qualify(schema, table),),
    )
    rows = await _fetch_dicts(cur)
  result: list[dict] = []
  for row in rows:
    result.append(
      {
        'constraint_name': row['constraint_name'],
        'definition': _decode_optional(row['definition']),
        'is_not_trusted': bool(row['is_not_trusted']),
        'is_disabled': bool(row['is_disabled']),
      }
    )
  logger.debug('list_check_constraints for %s.%s -> %d constraints', schema, table, len(result))
  return result


async def _table_schema(conn, schema_name: str, table: str):
  logger.debug('Building schema snapshot for table %s.%s', schema_name, table)
  columns = await list_columns(conn, schema_name, table)
  primary_key = await list_primary_key(conn, schema_name, table)
  foreign_keys = await list_foreign_keys(conn, schema_name, table)
  indexes = await list_indexes(conn, schema_name, table)
  constraints = await list_constraints(conn, schema_name, table)
  check_constraints = await list_check_constraints(conn, schema_name, table)
  schema = {
    'schema': schema_name,
    'name': _qualify(schema_name, table),
    'table': table,
    'columns': columns,
    'primary_key': primary_key,
    'foreign_keys': foreign_keys,
    'indexes': indexes,
    'constraints': constraints,
    'check_constraints': check_constraints,
  }
  logger.debug(
    'Completed schema snapshot for %s.%s: %d columns, %d FKs, %d indexes',
    schema_name,
    table,
    len(columns),
    len(foreign_keys),
    len(indexes),
  )
  return schema


async def get_schema(conn):
  tables = await list_tables(conn)
  logger.debug('get_schema processing %d tables', len(tables))
  schemas: dict[str, dict] = {}
  deps: dict[str, set[str]] = {}
  for t in tables:
    schema_name = t['table_schema']
    table_name = t['table_name']
    info = await _table_schema(conn, schema_name, table_name)
    key = f'{schema_name}.{table_name}'
    schemas[key] = info
    deps[key] = {
      f"{fk['ref_schema']}.{fk['ref_table']}"
      for fk in info['foreign_keys']
      if fk.get('ref_schema') and fk.get('ref_table')
    }
    logger.debug('Recorded dependencies for %s: %s', key, deps[key])
  ordered: list[str] = []
  visited: set[str] = set()

  def visit(name: str):
    if name in visited:
      return
    visited.add(name)
    for dep in deps.get(name, set()):
      if dep in deps:
        visit(dep)
    ordered.append(name)

  for table_name in deps.keys():
    visit(table_name)
  logger.debug('Table dependency order: %s', ordered)

  view_defs = await list_views(conn)
  view_map = {v['view_name']: v['view_definition'] for v in view_defs}
  logger.debug('get_schema processing %d views', len(view_map))
  view_deps: dict[str, set[str]] = {}
  for dep in await list_view_dependencies(conn):
    view_deps.setdefault(dep['view_name'], set()).add(dep['ref_name'])
  logger.debug('View dependencies: %s', view_deps)
  vordered: list[str] = []
  vvisited: set[str] = set()

  def visit_view(name: str):
    if name in vvisited:
      return
    vvisited.add(name)
    for dep in view_deps.get(name, set()):
      if dep in view_deps:
        visit_view(dep)
    vordered.append(name)

  for view_name in view_map.keys():
    visit_view(view_name)
  logger.debug('View dependency order: %s', vordered)

  schema_snapshot = {
    'tables': [schemas[n] for n in ordered],
    'views': [{'name': n, 'definition': view_map[n]} for n in vordered],
  }
  logger.debug(
    'Schema snapshot prepared with %d tables and %d views',
    len(schema_snapshot['tables']),
    len(schema_snapshot['views']),
  )
  return schema_snapshot


def _format_column(column: dict) -> str:
  ctype = column['data_type']
  length = column.get('max_length')
  precision = column.get('precision')
  scale = column.get('scale')
  computed = column.get('computed')
  if computed:
    definition = computed.strip()
    if not definition.upper().startswith('AS'):
      definition = f'AS {definition}'
    line = f"{_quote(column['name'])} {definition}"
  else:
    if ctype.lower() in {'varchar', 'nvarchar', 'char', 'nchar', 'varbinary', 'binary'}:
      if length == -1:
        ctype = f'{ctype}(MAX)'
      elif length is not None:
        if ctype.lower().startswith('n'):
          length = length // 2 if length else length
        ctype = f'{ctype}({length})'
    elif ctype.lower() in {'decimal', 'numeric'} and precision is not None:
      scale = scale or 0
      ctype = f'{ctype}({precision},{scale})'
    line = f"{_quote(column['name'])} {ctype}"
    if column.get('identity'):
      seed = column.get('identity_seed') or 1
      inc = column.get('identity_increment') or 1
      line += f' IDENTITY({seed},{inc})'
    default = column.get('default')
    if default:
      line += f' DEFAULT {default}'
    if not column.get('nullable', True):
      line += ' NOT NULL'
    if column.get('rowguidcol'):
      line += ' ROWGUIDCOL'
    if column.get('collation'):
      line += f" COLLATE {column['collation']}"
  return line


def _build_create_sql(table: dict) -> str:
  parts: list[str] = []
  for column in table['columns']:
    parts.append(_format_column(column))
  if table['primary_key']:
    pk_cols = ', '.join(_quote(col) for col in table['primary_key'])
    parts.append(f'PRIMARY KEY ({pk_cols})')
  for fk in table.get('foreign_keys', []):
    ref_schema = fk.get('ref_schema')
    ref_table = fk.get('ref_table')
    columns = fk.get('columns') or []
    ref_columns = fk.get('ref_columns') or []
    if not (ref_schema and ref_table and columns and ref_columns):
      continue
    ref = _qualify(ref_schema, ref_table)
    left = ', '.join(_quote(col) for col in columns)
    right = ', '.join(_quote(col) for col in ref_columns)
    clause = f"FOREIGN KEY ({left}) REFERENCES {ref}({right})"
    if fk.get('name'):
      clause = f"CONSTRAINT {_quote(fk['name'])} " + clause
    parts.append(clause)
  for constraint in table.get('constraints', []):
    ctype = (constraint.get('constraint_type') or '').upper()
    name = constraint.get('constraint_name')
    cols = constraint.get('columns')
    if ctype == 'UNIQUE' and cols:
      clause = f"CONSTRAINT {_quote(name)} UNIQUE ({cols})" if name else f"UNIQUE ({cols})"
      parts.append(clause)
  for chk in table.get('check_constraints', []):
    definition = chk.get('definition')
    if not definition:
      continue
    name = chk.get('constraint_name')
    trimmed = definition.strip()
    if trimmed.startswith('(') and trimmed.endswith(')'):
      check_body = trimmed
    else:
      check_body = f'({trimmed})'
    clause = f"CONSTRAINT {_quote(name)} CHECK {check_body}" if name else f"CHECK {check_body}"
    parts.append(clause)
  return f"CREATE TABLE {table['name']} ({', '.join(parts)})"


async def dump_schema(conn, prefix: str = 'schema') -> str:
  schema = await get_schema(conn)
  logger.debug(
    'dump_schema received %d tables and %d views',
    len(schema.get('tables', [])),
    len(schema.get('views', [])),
  )
  ts = datetime.now(timezone.utc).strftime('%Y%m%d')
  prefix_path = Path(prefix)
  base_name = prefix_path.name
  if prefix_path.is_absolute():
    target_dir = prefix_path.parent
  elif prefix_path.parent != Path('.'):
    target_dir = (ROOT / prefix_path.parent).resolve()
  else:
    target_dir = Path(__file__).resolve().parent
  target_dir.mkdir(parents=True, exist_ok=True)
  filename = f'{base_name}_{ts}.sql'
  out_path = target_dir / filename
  logger.debug('Writing schema dump to %s', out_path)
  lines: list[str] = []
  for table in schema['tables']:
    logger.debug('Serializing table %s', table['name'])
    lines.append(_build_create_sql(table) + ';')
    for idx in table.get('indexes', []):
      columns: list[str] = []
      included: list[str] = []
      for col in idx.get('columns', []):
        name = _quote(col['column_name'])
        if col.get('is_included'):
          included.append(name)
          continue
        direction = ' DESC' if col.get('is_descending') else ''
        columns.append(f'{name}{direction}')
      if not columns:
        continue
      statement = 'CREATE '
      if idx.get('is_unique'):
        statement += 'UNIQUE '
      statement += f"INDEX {idx['index_name']} ON {table['name']} ({', '.join(columns)})"
      if included:
        statement += f" INCLUDE ({', '.join(included)})"
      if idx.get('filter_definition'):
        statement += f" WHERE {idx['filter_definition']}"
      lines.append(statement + ';')
      logger.debug('Added index statement: %s', statement)
  for view in schema.get('views', []):
    raw_def = re.sub(r'--.*?(\r?\n|$)', ' ', view['definition'] or '')
    definition = ' '.join(raw_def.split())
    if not definition:
      continue
    if not definition.lower().startswith('create'):
      definition = f"CREATE VIEW {view['name']} AS {definition}"
    if not definition.endswith(';'):
      definition += ';'
    lines.append(definition)
    logger.debug('Added view definition for %s', view['name'])
  with open(out_path, 'w', encoding='utf-8') as fh:
    fh.write('\n'.join(lines))
  try:
    rel_path = out_path.relative_to(ROOT)
    result = rel_path.as_posix()
  except ValueError:
    result = str(out_path)
  print(f'Schema dumped to {result}')
  logger.debug('Schema dump complete: %s', result)
  return result


async def dump_data(conn, prefix: str = 'dump_data') -> str:
  schema = await get_schema(conn)
  logger.debug('dump_data processing %d tables', len(schema.get('tables', [])))
  data: dict[str, list[dict]] = {}
  for table in schema['tables']:
    async with conn.cursor() as cur:
      await cur.execute(f"SELECT * FROM {table['name']} FOR JSON PATH")
      rows = await _fetch_json(cur)
      data[table['name']] = rows
      logger.debug('dump_data captured %d rows for %s', len(rows), table['name'])
  ts = datetime.now(timezone.utc).strftime('%Y%m%d_BACKUP')
  filename = f'{prefix}_{ts}.json'
  with open(filename, 'w', encoding='utf-8') as fh:
    json.dump({'schema': schema, 'data': data}, fh, indent=2, default=str)
  print(f'Data dumped to {filename}')
  logger.debug('Data dump complete: %s', filename)
  return filename


async def apply_schema(conn, path: str):
  logger.debug('Applying schema from %s', path)
  with open(path, 'r', encoding='utf-8') as fh:
    sql = fh.read()
  async with conn.cursor() as cur:
    executed = 0
    for statement in sql.split(';'):
      stmt = statement.strip()
      if not stmt:
        continue
      logger.debug('Executing schema statement %d: %s', executed + 1, stmt[:120])
      await cur.execute(stmt)
      executed += 1
  logger.debug('Applied %d statements from %s', executed, path)
  print('Schema applied.')


async def connect(dbname: str | None = None):
  logger.debug('connect requested for database override %s', dbname)
  try:
    import aioodbc  # type: ignore
  except Exception as exc:
    raise ImportError('aioodbc is required for database operations') from exc
  dsn = os.getenv('AZURE_SQL_CONNECTION_STRING')
  if not dsn:
    raise RuntimeError('AZURE_SQL_CONNECTION_STRING not set')
  if dbname:
    parts = []
    replaced = False
    for part in dsn.split(';'):
      upper = part.upper()
      if upper.startswith('DATABASE=') or upper.startswith('INITIAL CATALOG='):
        parts.append(f'DATABASE={dbname}')
        replaced = True
      else:
        parts.append(part)
    if not replaced:
      parts.append(f'DATABASE={dbname}')
    dsn = ';'.join(parts)
  logger.debug('Establishing aioodbc connection (override applied=%s)', bool(dbname))
  conn = await aioodbc.connect(dsn=dsn, autocommit=True)
  print(f'Connected to database {dbname or dsn}')
  logger.debug('Connection established successfully')
  return conn
