from __future__ import annotations
import os, importlib.util, types, json, dotenv, re
from typing import Any, Union, get_origin, get_args
from pydantic import BaseModel
from pathlib import Path
from datetime import datetime, timezone


dotenv.load_dotenv()

# Root of the repository relative to this file
REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))

# Root of the solution using Pathlib
ROOT = Path(__file__).resolve().parent.parent

# Map bare Python types to TS primitives (won't be used for generic types)
PY_TO_TS = {
  str: 'string',
  int: 'number',
  float: 'number',
  bool: 'boolean',
  type(None): 'null',
  dict: 'Record<string, any>',
  datetime: 'string',
  list: 'any[]',  # fallback for untyped list
}

# Standard header included at the top of generated files
HEADER_COMMENT = [
  "// ================================================",
  "// WARNING: This file is automatically generated.",
  "// Do not modify it by hand. Your changes will be",
  "// overwritten the next time the generator runs.",
  "// ================================================",
  "",
]


def camel_case(name: str) -> str:
  """Convert snake_case names to CamelCase."""
  return "".join(part.capitalize() for part in name.split("_"))


def load_module(path: str) -> types.ModuleType:
  module_name = os.path.splitext(os.path.basename(path))[0] + "_tmp"
  spec = importlib.util.spec_from_file_location(module_name, path)
  if not spec or not spec.loader:
    raise ImportError(f"Could not load spec for module at {path}")
  module = importlib.util.module_from_spec(spec)
  spec.loader.exec_module(module)
  return module


def py_to_ts(py_type: Any) -> str:
  origin = get_origin(py_type)
  args = get_args(py_type)

  # Handle generics: List[X] or Tuple[X, ...]
  if origin in (list, tuple):
    inner_type = py_to_ts(args[0]) if args else 'any'
    return f"{inner_type}[]"

  # Handle Optional[X] (i.e. Union[X, None])
  if origin is Union:
    non_none = [arg for arg in args if arg is not type(None)]
    if len(non_none) == 1:
      return f"{py_to_ts(non_none[0])} | null"
    return " | ".join(py_to_ts(arg) for arg in args)

  # Known primitives
  if py_type in PY_TO_TS:
    return PY_TO_TS[py_type]

  # Pydantic models → use interface name
  if isinstance(py_type, type) and issubclass(py_type, BaseModel):
    return py_type.__name__

  # Fallback
  return 'any'


def model_to_ts(model: type[BaseModel]) -> str:
  lines = [f"export interface {model.__name__} {{"]
  fields = getattr(model, 'model_fields', None) or getattr(model, '__fields__', {})
  for name, field in fields.items():
    annotation = getattr(field, 'annotation', None) or getattr(field, 'outer_type_', None)
    ts_type = py_to_ts(annotation)
    lines.append(f"  {name}: {ts_type};")
  lines.append("}")
  return "\n".join(lines)


def parse_version(ver: str) -> tuple[int, int, int, int]:
  """Convert a version string like 'v1.2.3.4' into its numeric parts."""
  ver = ver.lstrip('v')
  major, minor, patch, build = [int(p) for p in ver.split('.')]
  return major, minor, patch, build


def next_build(current_version: str, last_version: str) -> int:
  """Return the next build number for the given versions.

  The build number is reset only when the major or minor version changes.
  Patch version bumps continue the build count within the same minor version.
  """
  cur_major, cur_minor, _, cur_build = parse_version(current_version)
  last_major, last_minor, _, _ = parse_version(last_version)
  if (cur_major, cur_minor) != (last_major, last_minor):
    return 1
  return cur_build + 1


def bump_version(version: str, part: str) -> str:
  """Increment the specified part of a version string.

  Parts can be 'major', 'minor', 'patch', or 'build'.
  Major/minor bumps reset lower-order fields to 0.
  """
  ma, mi, pa, bu = parse_version(version)
  match part:
    case 'major':
      ma += 1
      mi = 0
      pa = 0
      bu = 0
    case 'minor':
      mi += 1
      pa = 0
      bu = 0
    case 'patch':
      pa += 1
    case 'build':
      bu += 1
    case _:
      raise ValueError(f"Unknown part: {part}")
  return f"v{ma}.{mi}.{pa}.{bu}"

async def _fetch_json(cur):
  parts: list[str] = []
  while True:
    row = await cur.fetchone()
    if not row:
      break
    parts.append(row[0])
  return json.loads(''.join(parts)) if parts else []

async def _fetch_dicts(cur):
  rows = await cur.fetchall()
  if not rows:
    return []
  cols = [d[0] for d in cur.description]
  return [dict(zip(cols, row)) for row in rows]

def _decode_optional(value):
  if value is None:
    return None
  if isinstance(value, memoryview):
    value = value.tobytes()
  if isinstance(value, (bytes, bytearray)):
    return value.decode('utf-16le')
  return value

def _quote(name: str) -> str:
  return '[' + name.replace(']', ']]') + ']'

def _qualify(schema: str, name: str) -> str:
  return f"{_quote(schema)}.{_quote(name)}"

async def list_tables(conn):
  async with conn.cursor() as cur:
    await cur.execute(
      "SELECT TABLE_NAME AS table_name FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE='BASE TABLE' FOR JSON PATH"
    )
    return await _fetch_json(cur)

async def list_views(conn):
  async with conn.cursor() as cur:
    await cur.execute(
      """SELECT SCHEMA_NAME(v.schema_id) AS view_schema,
                v.name AS view_name,
                CONVERT(VARBINARY(MAX), m.definition) AS view_definition
           FROM sys.views v
           JOIN sys.sql_modules m ON v.object_id = m.object_id
          WHERE SCHEMA_NAME(v.schema_id)='dbo'
           FOR JSON PATH"""
    )
    rows = await _fetch_dicts(cur)
    for row in rows:
      row['view_definition'] = _decode_optional(row['view_definition'])
    return rows

async def list_view_dependencies(conn):
  async with conn.cursor() as cur:
    await cur.execute(
      """SELECT OBJECT_NAME(d.referencing_id) AS view_name,
                OBJECT_NAME(d.referenced_id) AS ref_name
           FROM sys.sql_expression_dependencies d
           JOIN sys.views v ON d.referencing_id = v.object_id
           JOIN sys.views r ON d.referenced_id = r.object_id
          WHERE SCHEMA_NAME(v.schema_id)='dbo'
            AND SCHEMA_NAME(r.schema_id)='dbo'
           FOR JSON PATH"""
    )
    return await _fetch_json(cur)

async def list_columns(conn, table):
  async with conn.cursor() as cur:
    await cur.execute(
      """SELECT c.name AS column_name,
                t.name AS data_type,
                c.max_length,
                c.precision,
                c.scale,
                c.is_nullable,
                CONVERT(VARBINARY(MAX), dc.definition) AS default_definition,
                ic.seed_value,
                ic.increment_value,
                c.is_identity,
                c.is_rowguidcol,
                CONVERT(VARBINARY(MAX), cc.definition) AS computed_definition,
                cc.is_persisted,
                c.collation_name
           FROM sys.columns c
           JOIN sys.types t
             ON c.user_type_id = t.user_type_id
          LEFT JOIN sys.default_constraints dc
             ON c.default_object_id = dc.object_id
          LEFT JOIN sys.identity_columns ic
             ON c.object_id = ic.object_id AND c.column_id = ic.column_id
          LEFT JOIN sys.computed_columns cc
             ON c.object_id = cc.object_id AND c.column_id = cc.column_id
          WHERE c.object_id = OBJECT_ID(?)
          ORDER BY c.column_id""",
      (f"{schema}.{table}",),
    )
    rows = await _fetch_dicts(cur)
    for row in rows:
      row['default_definition'] = _decode_optional(row['default_definition'])
      row['computed_definition'] = _decode_optional(row['computed_definition'])
    return rows

def _group_key_columns(rows: list[dict]) -> list[str]:
  ordered: list[str] = []
  for row in sorted(rows, key=lambda r: r['key_ordinal'] or 0):
    col = _quote(row['column_name'])
    if row.get('is_descending_key'):
      col += ' DESC'
    ordered.append(col)
  return ordered

async def _table_schema(conn, schema: str, table: str):
  raw_columns = await list_columns(conn, schema, table)
  columns: list[dict] = []
  for col in raw_columns:
    columns.append(
      {
        'name': col['column_name'],
        'data_type': col['data_type'],
        'max_length': col['max_length'],
        'precision': col['precision'],
        'scale': col['scale'],
        'nullable': bool(col['is_nullable']),
        'default': col['default_definition'],
        'identity': bool(col['is_identity']),
        'identity_seed': col['seed_value'],
        'identity_increment': col['increment_value'],
        'rowguidcol': bool(col['is_rowguidcol']),
        'computed': col['computed_definition'],
        'computed_persisted': bool(col['is_persisted']),
        'collation': col['collation_name'],
      }
    )
    return await _fetch_json(cur)

async def list_indexes(conn, table):
  async with conn.cursor() as cur:
    await cur.execute(
      """SELECT i.name AS index_name,
                i.is_unique AS is_unique,
                i.filter_definition AS filter_definition,
                (
                  SELECT c.name AS column_name,
                         ic.is_descending_key AS is_descending,
                         ic.is_included_column AS is_included,
                         ic.key_ordinal AS ordinal
                    FROM sys.index_columns ic
                    JOIN sys.columns c ON ic.object_id = c.object_id AND ic.column_id = c.column_id
                   WHERE ic.object_id = i.object_id AND ic.index_id = i.index_id
                   ORDER BY ic.is_included_column, ic.key_ordinal
                   FOR JSON PATH
                ) AS columns
         FROM sys.indexes i
        WHERE i.object_id = OBJECT_ID(?)
          AND i.is_primary_key = 0
          AND i.is_hypothetical = 0
        FOR JSON PATH""",
      (table,),
    )
    indexes = await _fetch_json(cur)
  for idx in indexes:
    cols = json.loads(idx.get('columns') or '[]')
    idx['columns'] = cols
  return indexes

async def list_keys(conn, table):
  async with conn.cursor() as cur:
    await cur.execute(
      """SELECT k.CONSTRAINT_NAME AS constraint_name,
                k.COLUMN_NAME AS column_name,
                tc.CONSTRAINT_TYPE AS constraint_type
         FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE k
         JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
           ON k.CONSTRAINT_NAME = tc.CONSTRAINT_NAME
         WHERE k.TABLE_NAME=? FOR JSON PATH""",
      (table,),
    )
    return await _fetch_json(cur)

async def list_constraints(conn, table):
  async with conn.cursor() as cur:
    await cur.execute(
      """SELECT tc.CONSTRAINT_NAME AS constraint_name,
                tc.CONSTRAINT_TYPE AS constraint_type,
                STRING_AGG(k.COLUMN_NAME, ', ') WITHIN GROUP (ORDER BY k.ORDINAL_POSITION) AS columns
         FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
         LEFT JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE k
           ON tc.CONSTRAINT_NAME = k.CONSTRAINT_NAME
          AND tc.TABLE_SCHEMA = k.TABLE_SCHEMA
          AND tc.TABLE_NAME = k.TABLE_NAME
        WHERE tc.TABLE_NAME=?
        GROUP BY tc.CONSTRAINT_NAME, tc.CONSTRAINT_TYPE
        FOR JSON PATH""",
      (table,),
    )
    return await _fetch_json(cur)

async def list_check_constraints(conn, table):
  async with conn.cursor() as cur:
    await cur.execute(
      """SELECT cc.CONSTRAINT_NAME AS constraint_name,
                cc.CHECK_CLAUSE AS definition
         FROM INFORMATION_SCHEMA.CHECK_CONSTRAINTS cc
         JOIN INFORMATION_SCHEMA.CONSTRAINT_TABLE_USAGE ctu
           ON cc.CONSTRAINT_NAME = ctu.CONSTRAINT_NAME
          AND cc.CONSTRAINT_SCHEMA = ctu.TABLE_SCHEMA
        WHERE ctu.TABLE_NAME=?
        FOR JSON PATH""",
      (table,),
    )
    return await _fetch_json(cur)

async def _table_schema(conn, table: str):
  async with conn.cursor() as cur:
    await cur.execute(
      """SELECT cc.name AS constraint_name,
                CONVERT(VARBINARY(MAX), cc.definition) AS definition,
                cc.is_not_trusted,
                cc.is_disabled
           FROM sys.check_constraints cc
          WHERE cc.parent_object_id = OBJECT_ID(?)""",
      (f"{schema}.{table}",),
    )
    raw_checks = await _fetch_dicts(cur)

  check_constraints = [
    {
      'name': row['constraint_name'],
      'definition': _decode_optional(row['definition']),
      'is_not_trusted': bool(row['is_not_trusted']),
      'is_disabled': bool(row['is_disabled']),
    }
    for row in raw_checks
  ]

  async with conn.cursor() as cur:
    await cur.execute(
      """SELECT i.name AS index_name,
                i.is_unique,
                i.type_desc,
                i.has_filter,
                CONVERT(VARBINARY(MAX), i.filter_definition) AS filter_definition,
                ic.is_included_column,
                ic.key_ordinal,
                ic.index_column_id,
                ic.is_descending_key,
                c.name AS column_name
           FROM sys.indexes i
           JOIN sys.index_columns ic
             ON i.object_id = ic.object_id
            AND i.index_id = ic.index_id
           JOIN sys.columns c
             ON ic.object_id = c.object_id
            AND ic.column_id = c.column_id
          WHERE i.object_id = OBJECT_ID(?)
            AND i.is_primary_key = 0
            AND i.is_unique_constraint = 0
            AND i.[type] <> 0
            AND i.is_hypothetical = 0
            AND i.name IS NOT NULL
          ORDER BY i.name,
                   CASE WHEN ic.is_included_column = 0 THEN ic.key_ordinal ELSE ic.index_column_id END""",
      (f"{schema}.{table}",),
    )
    index_rows = await _fetch_dicts(cur)

  index_map: dict[str, dict] = {}
  for row in index_rows:
    entry = index_map.setdefault(
      row['index_name'],
      {
        'name': row['index_name'],
        'is_unique': bool(row['is_unique']),
        'type_desc': row['type_desc'],
        'has_filter': bool(row['has_filter']),
        'filter_definition': _decode_optional(row['filter_definition']),
        'key_columns': [],
        'included_columns': [],
      },
    )
    fks = await _fetch_json(cur)
  indexes = await list_indexes(conn, table)
  keys = await list_keys(conn, table)
  constraints = await list_constraints(conn, table)
  checks = await list_check_constraints(conn, table)
  return {
    'name': table,
    'columns': [
      {
        'name': c['name'],
        'type': c['type'],
        'length': c['length'],
        'nullable': c['nullable'] == 'YES',
        'default': c['default'],
      }
      for c in cols
    ],
    'primary_key': [r['column_name'] for r in pk],
    'foreign_keys': [
      {
        'column': fk['column_name'],
        'ref_table': fk['ref_table'],
        'ref_column': fk['ref_column'],
      }
      for fk in fks
    ],
    'indexes': indexes,
    'keys': keys,
    'constraints': constraints,
    'check_constraints': checks,
  }

async def get_schema(conn):
  tables = await list_tables(conn)
  schemas: dict[str, dict] = {}
  deps: dict[str, set[str]] = {}
  for t in tables:
    name = t['table_name']
    info = await _table_schema(conn, name)
    schemas[name] = info
    deps[name] = {fk['ref_table'] for fk in info['foreign_keys']}
  ordered: list[str] = []
  visited: set[str] = set()
  def visit(n: str):
    if n in visited:
      return
    visited.add(n)
    for d in deps.get(n, set()):
      if d in deps:
        visit(d)
    ordered.append(n)
  for t in deps.keys():
    visit(t)

  view_defs = await list_views(conn)
  view_map = {v['view_name']: v['view_definition'] for v in view_defs}
  view_deps: dict[str, set[str]] = {}
  for d in await list_view_dependencies(conn):
    view_deps.setdefault(d['view_name'], set()).add(d['ref_name'])
  vordered: list[str] = []
  vvisited: set[str] = set()
  def vvisit(n: str):
    if n in vvisited:
      return
    vvisited.add(n)
    for d in view_deps.get(n, set()):
      if d in view_deps:
        vvisit(d)
    vordered.append(n)
  for v in view_map.keys():
    vvisit(v)

  return {
    'tables': [schemas[n] for n in ordered],
    'views': [{'name': n, 'definition': view_map[n]} for n in vordered],
  }

def _build_create_sql(table: dict) -> str:
  parts: list[str] = []
  for col in table['columns']:
    ctype = col['type']
    if col.get('length') is not None and ctype.lower() in {
      'varchar', 'nvarchar', 'char', 'nchar', 'varbinary'
    }:
      if col['length'] == -1:
        ctype += '(MAX)'
      else:
        ctype += f"({col['length']})"
    line = f"{col['name']} {ctype}"
    if col['default'] is not None:
      line += f" DEFAULT {col['default']}"
    if not col['nullable']:
      line += ' NOT NULL'
    parts.append(line)
  if table['primary_key']:
    parts.append('PRIMARY KEY (' + ', '.join(table['primary_key']) + ')')
  for fk in table['foreign_keys']:
    parts.append(
      f"FOREIGN KEY ({fk['column']}) REFERENCES {fk['ref_table']}({fk['ref_column']})"
    )
  for constraint in table.get('constraints', []):
    ctype = constraint.get('constraint_type', '').upper()
    name = constraint.get('constraint_name')
    cols = constraint.get('columns')
    if ctype == 'UNIQUE' and cols:
      clause = f"CONSTRAINT {name} UNIQUE ({cols})" if name else f"UNIQUE ({cols})"
      parts.append(clause)
  for chk in table.get('check_constraints', []):
    definition = chk.get('definition')
    if not definition:
      continue
    name = chk.get('constraint_name')
    trimmed = definition.strip()
    if trimmed.startswith('(') and trimmed.endswith(')'):
      check_body = trimmed
    else:
      check_body = f"({definition})"
    clause = f"CONSTRAINT {name} CHECK {check_body}" if name else f"CHECK {check_body}"
    parts.append(clause)
  return f"CREATE TABLE {table['name']} ({', '.join(parts)})"

async def dump_schema(conn, prefix: str = 'schema') -> str:
  schema = await get_schema(conn)
  ts = datetime.now(timezone.utc).strftime('%Y%m%d')
  prefix_path = Path(prefix)
  base_name = prefix_path.name
  target_dir: Path
  if prefix_path.is_absolute():
    target_dir = prefix_path.parent
  elif prefix_path.parent != Path('.'):
    target_dir = (ROOT / prefix_path.parent).resolve()
  else:
    target_dir = Path(__file__).resolve().parent
  target_dir.mkdir(parents=True, exist_ok=True)
  filename = f"{base_name}_{ts}.sql"
  out_path = target_dir / filename
  lines: list[str] = []
  for table in schema['tables']:
    lines.append(_build_create_sql(table) + ';')
    for idx in table.get('indexes', []):
      columns: list[str] = []
      included: list[str] = []
      for col in idx.get('columns', []):
        col_name = col['column_name']
        if col.get('is_included'):
          included.append(col_name)
          continue
        direction = ' DESC' if col.get('is_descending') else ''
        columns.append(f"{col_name}{direction}")
      if not columns:
        continue
      statement = 'CREATE '
      if idx.get('is_unique'):
        statement += 'UNIQUE '
      statement += f"INDEX {idx['index_name']} ON {table['name']} ({', '.join(columns)})"
      if included:
        statement += f" INCLUDE ({', '.join(included)})"
      if idx.get('filter_definition'):
        statement += f" WHERE {idx['filter_definition']}"
      lines.append(statement + ';')
  for view in schema.get('views', []):
    raw_def = re.sub(r'--.*?(\r?\n|$)', ' ', view['definition'])
    definition = ' '.join(raw_def.split())
    if not definition.lower().startswith('create'):
      definition = f"CREATE VIEW {view['name']} AS {definition}"
    if not definition.endswith(';'):
      definition += ';'
    lines.append(definition)
  with open(out_path, 'w') as f:
    f.write('\n'.join(lines))
  try:
    rel_path = out_path.relative_to(ROOT)
    result = rel_path.as_posix()
  except ValueError:
    result = str(out_path)
  print(f'Schema dumped to {result}')
  return result

async def dump_data(conn, prefix: str = 'dump_data') -> str:
  schema = await get_schema(conn)
  data: dict[str, list[dict]] = {}
  for tbl in schema['tables']:
    name = tbl['name']
    async with conn.cursor() as cur:
      await cur.execute(f"SELECT * FROM {name} FOR JSON PATH")
      data[name] = await _fetch_json(cur)
  ts = datetime.now(timezone.utc).strftime('%Y%m%d_BACKUP')
  filename = f"{prefix}_{ts}.json"
  with open(filename, 'w') as f:
    json.dump({'schema': schema, 'data': data}, f, indent=2, default=str)
  print(f'Data dumped to {filename}')
  return filename

async def apply_schema(conn, path: str):
  with open(path, 'r') as f:
    sql = f.read()
  async with conn.cursor() as cur:
    for stmt in sql.split(';'):
      stmt = stmt.strip()
      if not stmt:
        continue
      await cur.execute(stmt)
  print('Schema applied.')

async def connect(dbname=None):
  try:
    import aioodbc  # type: ignore
  except Exception as e:
    raise ImportError('aioodbc is required for database operations') from e
  dsn = os.getenv('AZURE_SQL_CONNECTION_STRING')
  if not dsn:
    raise RuntimeError('AZURE_SQL_CONNECTION_STRING not set')
  if dbname:
    parts = []
    replaced = False
    for part in dsn.split(';'):
      if part.upper().startswith('DATABASE=') or part.upper().startswith('INITIAL CATALOG='):
        parts.append(f'DATABASE={dbname}')
        replaced = True
      else:
        parts.append(part)
    if not replaced:
      parts.append(f'DATABASE={dbname}')
    dsn = ';'.join(parts)
  conn = await aioodbc.connect(dsn=dsn, autocommit=True)
  print(f'Connected to database {dbname or dsn}')
  return conn
