// ================================================
// WARNING: This file is automatically generated.
// Do not modify it by hand. Your changes will be
// overwritten the next time the generator runs.
// ================================================

import { rpcCall } from '../../../shared/RpcModels';

export const fetchPublicFiles = (payload: any = null): Promise<any> => rpcCall('urn:public:gallery:get_public_files:1', payload);
