// ================================================
// WARNING: This file is automatically generated.
// Do not modify it by hand. Your changes will be
// overwritten the next time the generator runs.
// ================================================

import { rpcCall, SystemVarsFfmpegVersion1, SystemVarsHostname1, SystemVarsRepo1, SystemVarsVersion1 } from '../../../shared/RpcModels';

export const fetchVersion = (payload: any = null): Promise<SystemVarsVersion1> => rpcCall('urn:system:vars:get_version:1', payload);
export const fetchHostname = (payload: any = null): Promise<SystemVarsHostname1> => rpcCall('urn:system:vars:get_hostname:1', payload);
export const fetchRepo = (payload: any = null): Promise<SystemVarsRepo1> => rpcCall('urn:system:vars:get_repo:1', payload);
export const fetchFfmpegVersion = (payload: any = null): Promise<SystemVarsFfmpegVersion1> => rpcCall('urn:system:vars:get_ffmpeg_version:1', payload);
