// ================================================
// WARNING: This file is automatically generated.
// Do not modify it by hand. Your changes will be
// overwritten the next time the generator runs.
// ================================================

import { rpcCall, SystemRolesList1 } from '../../../shared/RpcModels';

export const fetchList = (payload: any = null): Promise<SystemRolesList1> => rpcCall('urn:system:roles:list:1', payload);
export const fetchSet = (payload: any = null): Promise<any> => rpcCall('urn:system:roles:set:1', payload);
export const fetchDelete = (payload: any = null): Promise<any> => rpcCall('urn:system:roles:delete:1', payload);
