// ================================================
// WARNING: This file is automatically generated.
// Do not modify it by hand. Your changes will be
// overwritten the next time the generator runs.
// ================================================

import { rpcCall } from '../../../shared/RpcModels';

export const fetchVersions = (payload: any = null): Promise<any> => rpcCall('urn:public:vars:get_versions:1', payload);
