// ================================================
// WARNING: This file is automatically generated.
// Do not modify it by hand. Your changes will be
// overwritten the next time the generator runs.
// ================================================

import { rpcCall } from '../../../shared/RpcModels';

export const fetchVersion = (payload: any = null): Promise<any> => rpcCall('urn:public:vars:get_version:1', payload);
export const fetchHostname = (payload: any = null): Promise<any> => rpcCall('urn:public:vars:get_hostname:1', payload);
export const fetchRepo = (payload: any = null): Promise<any> => rpcCall('urn:public:vars:get_repo:1', payload);
export const fetchFfmpegVersion = (payload: any = null): Promise<any> => rpcCall('urn:public:vars:get_ffmpeg_version:1', payload);
export const fetchOdbcVersion = (payload: any = null): Promise<any> => rpcCall('urn:public:vars:get_odbc_version:1', payload);
