// ================================================
// WARNING: This file is automatically generated.
// Do not modify it by hand. Your changes will be
// overwritten the next time the generator runs.
// ================================================

import { rpcCall } from '../../../shared/RpcModels';

export const fetchList = (payload: any = null): Promise<any> => rpcCall('urn:finance:journals:list:1', payload);
export const fetchGet = (payload: any = null): Promise<any> => rpcCall('urn:finance:journals:get:1', payload);
export const fetchLines = (payload: any = null): Promise<any> => rpcCall('urn:finance:journals:get_lines:1', payload);
export const fetchCreate = (payload: any = null): Promise<any> => rpcCall('urn:finance:journals:create:1', payload);
export const fetchSubmitForApproval = (payload: any = null): Promise<any> => rpcCall('urn:finance:journals:submit_for_approval:1', payload);
export const fetchApprove = (payload: any = null): Promise<any> => rpcCall('urn:finance:journals:approve:1', payload);
export const fetchReject = (payload: any = null): Promise<any> => rpcCall('urn:finance:journals:reject:1', payload);
export const fetchReverse = (payload: any = null): Promise<any> => rpcCall('urn:finance:journals:reverse:1', payload);
