// ================================================
// WARNING: This file is automatically generated.
// Do not modify it by hand. Your changes will be
// overwritten the next time the generator runs.
// ================================================

import { rpcCall } from '../../../shared/RpcModels';

export const fetchList = (payload: any = null): Promise<any> => rpcCall('urn:finance:vendors:list:1', payload);
export const fetchUpsert = (payload: any = null): Promise<any> => rpcCall('urn:finance:vendors:upsert:1', payload);
export const fetchDelete = (payload: any = null): Promise<any> => rpcCall('urn:finance:vendors:delete:1', payload);
