// ================================================
// WARNING: This file is automatically generated.
// Do not modify it by hand. Your changes will be
// overwritten the next time the generator runs.
// ================================================

import { rpcCall } from '../../../shared/RpcModels';

export const fetchDisplayname = (payload: any = null): Promise<any> => rpcCall('urn:account:user:get_displayname:1', payload);
export const fetchCredits = (payload: any = null): Promise<any> => rpcCall('urn:account:user:get_credits:1', payload);
export const fetchSetCredits = (payload: any = null): Promise<any> => rpcCall('urn:account:user:set_credits:1', payload);
export const fetchResetDisplay = (payload: any = null): Promise<any> => rpcCall('urn:account:user:reset_display:1', payload);
export const fetchCreateFolder = (payload: any = null): Promise<any> => rpcCall('urn:account:user:create_folder:1', payload);
