# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - elideus-group-test

on:
  push:
    branches:
      - elideus
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'
    
    env:
      AZURE_SQL_CONNECTION_STRING: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r requirements-dev.txt

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Node dependencies
      run: |
        cd frontend
        npm ci

    - name: Generate RPC bindings
      run: |
        python scripts/generate_rpc_library.py
        python scripts/generate_rpc_client.py

    - name: Install MSSQL ODBC Driver
      run: |
        sudo apt-get update
        sudo apt-get install -y curl gnupg2 apt-transport-https ca-certificates unixodbc libodbc2
        curl -sSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /usr/share/keyrings/microsoft-prod.gpg > /dev/null
        echo "deb [signed-by=/usr/share/keyrings/microsoft-prod.gpg] https://packages.microsoft.com/debian/12/prod bookworm main" | sudo tee /etc/apt/sources.list.d/mssql-release.list
        sudo apt-get update
        sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18

    - name: Run tests
      run: python scripts/run_tests.py

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://elideus.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_375ace388d15453497189874787dd593 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_5aa3578f604f4524bb044702bea92778 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: elideus.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_375ace388d15453497189874787dd593 }}/elideus-group-test:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'elideus-group-test'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_87c95834367a4a4fb2f68acf9aea62c2 }}
        images: 'elideus.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_375ace388d15453497189874787dd593 }}/elideus-group-test:${{ github.sha }}'
