// ================================================
// WARNING: This file is automatically generated.
// Do not modify it by hand. Your changes will be
// overwritten the next time the generator runs.
// ================================================

import { rpcCall } from '../../../shared/RpcModels';

export const fetchList = (payload: any = null): Promise<any> => rpcCall('urn:system:batch_jobs:list:1', payload);
export const fetchGet = (payload: any = null): Promise<any> => rpcCall('urn:system:batch_jobs:get:1', payload);
export const fetchUpsert = (payload: any = null): Promise<any> => rpcCall('urn:system:batch_jobs:upsert:1', payload);
export const fetchDelete = (payload: any = null): Promise<any> => rpcCall('urn:system:batch_jobs:delete:1', payload);
export const fetchListHistory = (payload: any = null): Promise<any> => rpcCall('urn:system:batch_jobs:list_history:1', payload);
export const fetchRunNow = (payload: any = null): Promise<any> => rpcCall('urn:system:batch_jobs:run_now:1', payload);
